# **Feature Generation Notebook**
The purpose of this notebook is to generate and save the features for modeling

## **1.0: Package and Data Load**

In [171]:
import pandas as pd
import numpy as np
import pickle

In [2]:
tw1 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw1_processed.csv')
tw2 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw2_processed.csv')
tw3 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw3_processed.csv')
tw4 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw4_processed.csv')
tw5 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw5_processed.csv')
tw6 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw6_processed.csv')
tw7 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw7_processed.csv')
tw8 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw8_processed.csv')
tw9 = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tw9_processed.csv')

In [6]:
games = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/games.csv')
plays = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/plays.csv')
players = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/players.csv')
tackles = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/tackles.csv')

In [8]:
#Function to create 'game_play_Id' column in DF
def game_play_Id(df):
    df['game_play_Id'] = df['gameId'].astype('str') + '_' + df['playId'].astype('str')

    return df

In [9]:
plays = game_play_Id(plays)
tackles = game_play_Id(tackles)

In [20]:
plays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12486 entries, 0 to 12485
Data columns (total 36 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   gameId                            12486 non-null  int64  
 1   playId                            12486 non-null  int64  
 2   ballCarrierId                     12486 non-null  int64  
 3   ballCarrierDisplayName            12486 non-null  object 
 4   playDescription                   12486 non-null  object 
 5   quarter                           12486 non-null  int64  
 6   down                              12486 non-null  int64  
 7   yardsToGo                         12486 non-null  int64  
 8   possessionTeam                    12486 non-null  object 
 9   defensiveTeam                     12486 non-null  object 
 10  yardlineSide                      12319 non-null  object 
 11  yardlineNumber                    12486 non-null  int64  
 12  game

In [7]:
pd.set_option('display.max_columns', None)
tw1.head()

gameId  playId    nflId   displayName  frameId  \
0  2022090800      56  42489.0  Stefon Diggs        1   
1  2022090800      56  42489.0  Stefon Diggs        2   
2  2022090800      56  42489.0  Stefon Diggs        3   
3  2022090800      56  42489.0  Stefon Diggs        4   
4  2022090800      56  42489.0  Stefon Diggs        5   

                         time  jerseyNumber club playDirection      x      y  \
0  2022-09-08 20:24:05.200000          14.0  BUF          left  80.60  38.29   
1  2022-09-08 20:24:05.299999          14.0  BUF          left  80.48  37.68   
2  2022-09-08 20:24:05.400000          14.0  BUF          left  80.34  37.09   
3  2022-09-08 20:24:05.500000          14.0  BUF          left  80.19  36.53   
4  2022-09-08 20:24:05.599999          14.0  BUF          left  80.01  36.00   

      s     a   dis       o     dir         event   game_play_Id  \
0  6.23  0.90  0.62  140.05  189.38           NaN  2022090800_56   
1  6.24  1.27  0.62  134.22  191.08  pass_arrived  2022090800_56   
2  5.98  2.48  0.60  127.16  194.40           NaN  2022090800_56   
3  5.67  3.37  0.58  120.72  196.97           NaN  2022090800_56   
4  5.43  3.65  0.56  118.07  199.54           NaN  2022090800_56   

  defensiveTeam  ballCarrierId    bcx    bcy  bc_s  bc_a  bc_dis    bc_o  \
0            LA          42489  80.60  38.29  6.23  0.90    0.62  140.05   
1            LA          42489  80.48  37.68  6.24  1.27    0.62  134.22   
2            LA          42489  80.34  37.09  5.98  2.48    0.60  127.16   
3            LA          42489  80.19  36.53  5.67  3.37    0.58  120.72   
4            LA          42489  80.01  36.00  5.43  3.65    0.56  118.07   

   bc_dir  distance_from_bc  tackler_one  tackler_two  assister_one  \
0  189.38               0.0      43294.0          NaN           NaN   
1  191.08               0.0      43294.0          NaN           NaN   
2  194.40               0.0      43294.0          NaN           NaN   
3  196.97               0.0      43294.0          NaN           NaN   
4  199.54               0.0      43294.0          NaN           NaN   

   assister_two  missed_tackler_1  missed_tackler_2  missed_tackler_3  \
0           NaN               NaN               NaN               NaN   
1           NaN               NaN               NaN               NaN   
2           NaN               NaN               NaN               NaN   
3           NaN               NaN               NaN               NaN   
4           NaN               NaN               NaN               NaN   

   missed_tackler_4  missed_tackler_5  missed_tackler_6 new_event  cosine  \
0               NaN               NaN               NaN       NaN     1.0   
1               NaN               NaN               NaN       NaN     1.0   
2               NaN               NaN               NaN       NaN     1.0   
3               NaN               NaN               NaN       NaN     1.0   
4               NaN               NaN               NaN       NaN     1.0   

   do_align  bc_do_align  weight  bc_weight   force  bc_force  
0  0.451889     0.451889     191        191  171.90    171.90  
1  0.368222     0.368222     191        191  242.57    242.57  
2  0.252889     0.252889     191        191  473.68    473.68  
3  0.152778     0.152778     191        191  643.67    643.67  
4  0.094778     0.094778     191        191  697.15    697.15

## **2.0: Feature Generation**

### **2.1: Figuring out how many non-assist tackling events**

In [11]:
tackles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17426 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   gameId            17426 non-null  int64 
 1   playId            17426 non-null  int64 
 2   nflId             17426 non-null  int64 
 3   tackle            17426 non-null  int64 
 4   assist            17426 non-null  int64 
 5   forcedFumble      17426 non-null  int64 
 6   pff_missedTackle  17426 non-null  int64 
 7   game_play_Id      17426 non-null  object
dtypes: int64(7), object(1)
memory usage: 1.1+ MB


In [43]:
tackles_1v1 = tackles[(tackles['tackle'] == 1) | (tackles['pff_missedTackle'] == 1)]

In [44]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11974 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   gameId            11974 non-null  int64 
 1   playId            11974 non-null  int64 
 2   nflId             11974 non-null  int64 
 3   tackle            11974 non-null  int64 
 4   assist            11974 non-null  int64 
 5   forcedFumble      11974 non-null  int64 
 6   pff_missedTackle  11974 non-null  int64 
 7   game_play_Id      11974 non-null  object
dtypes: int64(7), object(1)
memory usage: 841.9+ KB


In [45]:
tackles_1v1.tackle.value_counts()

tackle
1    9919
0    2055
Name: count, dtype: int64

In [46]:
tackles_1v1.pff_missedTackle.value_counts()

pff_missedTackle
0    9884
1    2090
Name: count, dtype: int64

In [17]:
tackles_weird = tackles[(tackles['tackle'] == 1) & (tackles['pff_missedTackle'] == 1)]

In [28]:
tackles_weird.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 219 to 9620
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   gameId            35 non-null     int64 
 1   playId            35 non-null     int64 
 2   nflId             35 non-null     int64 
 3   tackle            35 non-null     int64 
 4   assist            35 non-null     int64 
 5   forcedFumble      35 non-null     int64 
 6   pff_missedTackle  35 non-null     int64 
 7   game_play_Id      35 non-null     object
dtypes: int64(7), object(1)
memory usage: 2.5+ KB


### **2.2: Creating Event Type Label**

In [47]:
# Function to determine event_type
def determine_event_type(row):
    if row['tackle'] == 1 and row['pff_missedTackle'] == 0:
        return 1
    elif row['tackle'] == 0 and row['pff_missedTackle'] == 1:
        return 2
    else:
        return None


In [48]:
# Apply the function to each row
tackles_1v1['event_type'] = tackles_1v1.apply(determine_event_type, axis=1)

# Find indices where both 'tackle' and 'pff_missedTackle' are 1
both_one_indices = tackles_1v1[(tackles_1v1['tackle'] == 1) & (tackles_1v1['pff_missedTackle'] == 1)].index

# Create duplicates of these rows
duplicates = tackles_1v1.loc[both_one_indices].copy()

# Modify the original rows
tackles_1v1.loc[both_one_indices, 'tackle'] = 0
tackles_1v1.loc[both_one_indices, 'event_type'] = 2

# Modify the duplicates
duplicates['pff_missedTackle'] = 0
duplicates['event_type'] = 1

# Concatenate the original DataFrame with the duplicates
tackles_1v1 = pd.concat([tackles_1v1, duplicates])

/var/folders/38/1m7d78r13mngspmlwjmj74480000gn/T/ipykernel_39743/2649901282.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tackles_1v1['event_type'] = tackles_1v1.apply(determine_event_type, axis=1)


In [49]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12009 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            12009 non-null  int64  
 1   playId            12009 non-null  int64  
 2   nflId             12009 non-null  int64  
 3   tackle            12009 non-null  int64  
 4   assist            12009 non-null  int64  
 5   forcedFumble      12009 non-null  int64  
 6   pff_missedTackle  12009 non-null  int64  
 7   game_play_Id      12009 non-null  object 
 8   event_type        12009 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 938.2+ KB


In [130]:
tackles_1v1.event_type.value_counts()

event_type
1.0    9919
2.0    2090
Name: count, dtype: int64

In [129]:
tackles_1v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12009 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            12009 non-null  int64  
 1   playId            12009 non-null  int64  
 2   nflId             12009 non-null  int64  
 3   tackle            12009 non-null  int64  
 4   assist            12009 non-null  int64  
 5   forcedFumble      12009 non-null  int64  
 6   pff_missedTackle  12009 non-null  int64  
 7   game_play_Id      12009 non-null  object 
 8   event_type        12009 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 938.2+ KB


### **2.3: Combining all tracking data into one df**

In [142]:
tw1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154194 entries, 0 to 154193
Data columns (total 46 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   gameId            154194 non-null  int64  
 1   playId            154194 non-null  int64  
 2   nflId             154194 non-null  float64
 3   displayName       154194 non-null  object 
 4   frameId           154194 non-null  int64  
 5   time              154194 non-null  object 
 6   jerseyNumber      154194 non-null  float64
 7   club              154194 non-null  object 
 8   playDirection     154194 non-null  object 
 9   x                 154194 non-null  float64
 10  y                 154194 non-null  float64
 11  s                 154194 non-null  float64
 12  a                 154194 non-null  float64
 13  dis               154194 non-null  float64
 14  o                 154194 non-null  float64
 15  dir               154194 non-null  float64
 16  event             13

In [132]:
tracking_clean = pd.concat([tw1, tw2, tw3, tw4, tw5, tw6, tw7, tw8, tw9], ignore_index=True)

In [154]:
tracking_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1334038 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1334038 non-null  int64  
 1   playId            1334038 non-null  int64  
 2   nflId             1334038 non-null  float64
 3   displayName       1334038 non-null  object 
 4   frameId           1334038 non-null  int64  
 5   time              1334038 non-null  object 
 6   jerseyNumber      1334038 non-null  float64
 7   club              1334038 non-null  object 
 8   playDirection     1334038 non-null  object 
 9   x                 1334038 non-null  float64
 10  y                 1334038 non-null  float64
 11  s                 1334038 non-null  float64
 12  a                 1334038 non-null  float64
 13  dis               1334038 non-null  float64
 14  o                 1334038 non-null  float64
 15  dir               1334038 non-null  float64
 16  

In [155]:
###Saving Tracking Clean (Still has all observations)
tracking_clean.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean.csv', index=False)

### **2.4: Deleting Observations without a second of data beforehand**

In [615]:
def check_indices(df):
    # Get the indices of the rows where 'event' is 'tackle' and 'nflId' is not equal to 'ballCarrierId'
    tackle_indices = df[(df['event'] == 'first_contact') & (df['nflId'] != df['ballCarrierId'])].index

    # Number of frames before 'tackle' event
    X = 10

    # Initialize count
    count = 0

    # List to store the indices where 'game_play_Id' and 'nflId' are different
    different_indices = []

    for idx in tackle_indices:
        # Check if the index X indices before exists in the DataFrame
        if idx - X in df.index:
            # Check if 'game_play_Id' and 'nflId' are the same
            if df.loc[idx, 'game_play_Id'] != df.loc[idx - X, 'game_play_Id'] or df.loc[idx, 'nflId'] != df.loc[idx - X, 'nflId']:
                count += 1
                different_indices.append(idx)

    # Print the indices where 'game_play_Id' and 'nflId' are different
    print('Indices where game_play_Id and nflId are different:', different_indices)

    # Print the count
    print('Count:', count)

    return different_indices

In [616]:
check_indices(tracking_clean_1)

Indices where game_play_Id and nflId are different: [640, 1148, 1415, 2079, 2436, 4734, 4750, 4769, 4827, 5544, 5589, 5849, 6615, 7087, 7161, 7220, 7965, 8001, 8178, 8962, 10858, 12197, 12633, 12899, 12928, 13454, 14123, 14156, 14211, 15390, 16450, 17262, 17544, 17639, 18599, 18940, 19260, 19705, 19760, 20367, 20934, 29255, 29272, 32223, 36300, 36321, 40298, 41001, 41036, 42226, 43173, 43560, 43772, 45697, 45737, 46430, 47264, 47694, 47752, 48228, 49097, 49744, 49796, 50649, 51387, 51419, 52013, 52728, 52745, 54042, 54236, 54282, 54949, 55358, 56141, 57294, 58851, 59262, 59294, 61681, 63079, 63099, 63228, 63446, 63507, 65122, 65326, 65518, 67737, 68939, 69657, 70668, 71030, 71112, 71154, 71637, 72548, 72608, 74012, 74085, 74756, 75285, 77204, 77253, 77302, 77350, 77406, 77948, 78011, 78231, 79459, 79478, 79512, 80890, 81175, 81496, 82618, 84565, 84591, 84643, 87198, 87215, 87247, 87318, 87717, 87805, 88471, 88793, 88815, 88870, 89440, 90300, 90352, 91546, 91580, 91926, 94997, 96668, 97

[640,
 1148,
 1415,
 2079,
 2436,
 4734,
 4750,
 4769,
 4827,
 5544,
 5589,
 5849,
 6615,
 7087,
 7161,
 7220,
 7965,
 8001,
 8178,
 8962,
 10858,
 12197,
 12633,
 12899,
 12928,
 13454,
 14123,
 14156,
 14211,
 15390,
 16450,
 17262,
 17544,
 17639,
 18599,
 18940,
 19260,
 19705,
 19760,
 20367,
 20934,
 29255,
 29272,
 32223,
 36300,
 36321,
 40298,
 41001,
 41036,
 42226,
 43173,
 43560,
 43772,
 45697,
 45737,
 46430,
 47264,
 47694,
 47752,
 48228,
 49097,
 49744,
 49796,
 50649,
 51387,
 51419,
 52013,
 52728,
 52745,
 54042,
 54236,
 54282,
 54949,
 55358,
 56141,
 57294,
 58851,
 59262,
 59294,
 61681,
 63079,
 63099,
 63228,
 63446,
 63507,
 65122,
 65326,
 65518,
 67737,
 68939,
 69657,
 70668,
 71030,
 71112,
 71154,
 71637,
 72548,
 72608,
 74012,
 74085,
 74756,
 75285,
 77204,
 77253,
 77302,
 77350,
 77406,
 77948,
 78011,
 78231,
 79459,
 79478,
 79512,
 80890,
 81175,
 81496,
 82618,
 84565,
 84591,
 84643,
 87198,
 87215,
 87247,
 87318,
 87717,
 87805,
 88471,
 8879

In [161]:
missing_indices_07 = check_indices(tracking_clean)

Indices where game_play_Id and nflId are different: [14063, 14074, 17612, 17623, 20579, 20590, 51887, 51898, 91263, 91274, 91562, 91573, 106329, 106340, 119489, 119500, 136398, 136409, 144658, 144669, 144878, 144889, 154658, 154669, 191539, 191550, 230405, 230416, 243028, 243039, 255160, 255171, 276491, 276502, 290376, 290387, 348106, 348117, 385470, 385481, 401427, 401438, 424743, 424754, 432652, 432663, 450031, 450042, 459968, 459979, 479700, 479711, 486440, 486451, 521657, 521668, 524722, 524733, 564815, 564826, 581886, 581897, 599640, 599651, 604195, 604206, 604781, 604792, 644283, 644294, 654830, 654841, 657479, 657490, 666904, 666915, 695217, 695228, 718709, 718720, 723525, 723536, 737745, 737756, 767105, 767116, 786301, 786312, 820288, 820299, 867588, 867599, 924264, 924275, 946608, 946619, 953235, 953246, 1002689, 1002700, 1002711, 1002722, 1036794, 1036805, 1148633, 1148644, 1191458, 1191469, 1196551, 1196562, 1314707, 1314718, 1316210, 1316221, 1318480, 1318491, 1319282, 1319

In [177]:
missing_indices_1 = check_indices(tracking_clean)

Indices where game_play_Id and nflId are different: [1315, 1327, 2656, 2670, 14063, 14074, 17612, 17623, 17635, 17647, 18586, 18600, 20579, 20590, 21210, 21223, 28372, 28385, 33582, 38659, 38673, 39329, 39343, 43404, 43416, 46962, 46975, 47234, 47246, 50191, 50205, 51887, 51898, 54749, 54761, 55128, 55141, 60335, 60347, 66088, 66101, 76756, 76769, 76851, 76863, 77770, 77782, 83988, 84001, 90209, 90222, 91263, 91274, 91562, 91573, 92539, 92553, 96571, 96583, 96964, 96977, 98068, 98082, 98508, 98522, 106329, 106340, 106353, 106366, 108474, 108487, 108500, 119489, 119500, 121755, 121769, 122518, 122532, 127548, 127562, 136398, 136409, 138069, 138083, 139897, 139911, 140810, 140822, 142333, 142347, 144658, 144669, 144878, 144889, 154658, 154669, 154779, 154791, 156073, 156087, 156694, 156707, 159833, 159845, 163121, 163133, 170023, 170036, 175554, 175568, 179355, 179369, 180149, 180161, 189038, 189052, 191539, 191550, 196635, 196648, 199053, 199067, 203011, 203023, 204547, 204559, 204704, 

In [384]:
missing_indices_fumble_1 = check_indices(tracking_clean_1)

Indices where game_play_Id and nflId are different: [79541, 123526, 444032, 969176]
Count: 4


In [239]:
missing_indices_1_no_bc = check_indices(tracking_clean)

Indices where game_play_Id and nflId are different: [1327, 2670, 14063, 17623, 17647, 18600, 20590, 21223, 28372, 38659, 39343, 43404, 46962, 47246, 50191, 51887, 54749, 55141, 60335, 66088, 76756, 76851, 77770, 84001, 90209, 91274, 91562, 92539, 96571, 96964, 98082, 98508, 106340, 106353, 108487, 108500, 119500, 121769, 122532, 127548, 136398, 138083, 139897, 140822, 142347, 144669, 144889, 154669, 154791, 156087, 156707, 159845, 163133, 170023, 175568, 179355, 180161, 189038, 191550, 196635, 199053, 203023, 204559, 204717, 204877, 204902, 205420, 205911, 209055, 209080, 212925, 215126, 220822, 226877, 229712, 230405, 237220, 237779, 243039, 254044, 254070, 255160, 263715, 263743, 271012, 276491, 280260, 281101, 287776, 288889, 290387, 290461, 291319, 291593, 305947, 310768, 311916, 311928, 317394, 324550, 327023, 327061, 340574, 342947, 348106, 348722, 349355, 352754, 354068, 355583, 357799, 374201, 378109, 378133, 381446, 382244, 382270, 383183, 383780, 385470, 387254, 391634, 39510

**Checking if any indices are in 'missing_indices_07' but are not in 'missing_indices_1'**

In [184]:
# Convert the lists to sets
set_07 = set(missing_indices_07)
set_1 = set(missing_indices_1)

# Find the elements that are in set_07 but not in set_1
difference = set_07.difference(set_1)

# Print the number of such elements
print(len(difference))

0


In [172]:
# Define the path to the folder where you want to save the file
folder_path = '/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/'

In [173]:
###Save list of Tackle Indices for 7 frames before
with open(folder_path + 'missed_indices_07.pkl', 'wb') as f:
    pickle.dump(missing_indices_07, f)

In [178]:
###Save list of Tackle Indices for 10 frames before
with open(folder_path + 'missing_indices_1.pkl', 'wb') as f:
    pickle.dump(missing_indices_1, f)

In [240]:
###Function to check number of indicies that they there is data for missed tackles
def check_indices_mt(df):
    # Get the indices of the rows where 'event' is 'tackle'
    missed_tackle_indices = df[(df['new_event'] == 'missed tackle') & (df['nflId'] != df['ballCarrierId'])].index

    # Number of frames before 'tackle' event
    X = 10

    # Initialize count
    count = 0

    # List to store the indices where 'game_play_Id' and 'nflId' are different
    different_indices = []

    for idx in missed_tackle_indices:
        # Check if the index X indices before exists in the DataFrame
        if idx - X in df.index:
            # Check if 'game_play_Id' and 'nflId' are the same
            if df.loc[idx, 'game_play_Id'] != df.loc[idx - X, 'game_play_Id'] or df.loc[idx, 'nflId'] != df.loc[idx - X, 'nflId']:
                count += 1
                different_indices.append(idx)

    # Print the indices where 'game_play_Id' and 'nflId' are different
    print('Indices where game_play_Id and nflId are different:', different_indices)

    # Print the count
    print('Count:', count)

    return different_indices

In [163]:
missing_indices_mt_07 = check_indices_mt(tracking_clean)

Indices where game_play_Id and nflId are different: [12922, 34725, 51731, 52779, 55640, 57411, 58035, 68848, 86381, 107019, 110595, 120597, 120631, 136338, 147996, 156674, 158520, 178125, 212823, 214636, 311921, 332121, 351489, 368915, 372788, 382782, 409111, 432892, 452750, 464894, 493174, 496035, 496049, 501513, 508341, 519990, 520018, 543770, 548232, 548310, 549377, 574471, 581048, 610460, 630315, 654434, 670021, 673241, 676171, 692371, 699997, 771085, 780654, 788532, 794968, 795241, 796630, 807953, 815705, 819585, 840445, 841241, 842578, 845521, 854124, 877829, 884016, 886686, 899833, 901033, 907655, 921162, 924949, 933033, 959407, 987203, 994045, 1047478, 1053698, 1060203, 1091799, 1124084, 1128294, 1136398, 1140202, 1150719, 1165152, 1177443, 1181479, 1194337, 1214065, 1214145, 1215864, 1218259, 1236455, 1239235, 1266063, 1272172, 1296186, 1307083]
Count: 100


In [180]:
missing_indices_mt_1 = check_indices_mt(tracking_clean)

Indices where game_play_Id and nflId are different: [12922, 19937, 34725, 44263, 48795, 51731, 52145, 52779, 55640, 57411, 58035, 59739, 64431, 68848, 73619, 78497, 83491, 86381, 88656, 99800, 107019, 110595, 117045, 120597, 120631, 136338, 147996, 148433, 155369, 156674, 158520, 177788, 178125, 192331, 193642, 212823, 214636, 216202, 225155, 226134, 244252, 263660, 298871, 301237, 306877, 311921, 317547, 323191, 327498, 332121, 341552, 350970, 351489, 356544, 368915, 372788, 380308, 380580, 382385, 382782, 398124, 409111, 427521, 432892, 436573, 444996, 452750, 464894, 466031, 493174, 496035, 496049, 501513, 508341, 519990, 520018, 543770, 548232, 548310, 549377, 557963, 574471, 581048, 592086, 596080, 610460, 623984, 630315, 636633, 654434, 668747, 670021, 673241, 676171, 692371, 699997, 706701, 712253, 713260, 723993, 729310, 730937, 731747, 752331, 764733, 771085, 771476, 780654, 788532, 794968, 795080, 795241, 796630, 796807, 807953, 809992, 812423, 815705, 819585, 819869, 823013,

In [241]:
missing_indices_mt_1_no_bc = check_indices_mt(tracking_clean)

Indices where game_play_Id and nflId are different: [12922, 19937, 34725, 44263, 48795, 51731, 52145, 52779, 55640, 57411, 58035, 59739, 64431, 68848, 73619, 78497, 83491, 86381, 88656, 99800, 107019, 110595, 117045, 120597, 120631, 136338, 147996, 148433, 155369, 156674, 158520, 177788, 178125, 192331, 193642, 212823, 214636, 216202, 225155, 226134, 244252, 263660, 298871, 301237, 306877, 311921, 317547, 323191, 327498, 332121, 341552, 350970, 351489, 356544, 368915, 372788, 380308, 380580, 382385, 382782, 398124, 409111, 427521, 432892, 436573, 444996, 452750, 464894, 466031, 493174, 496035, 496049, 501513, 508341, 519990, 520018, 543770, 548232, 548310, 549377, 557963, 574471, 581048, 592086, 596080, 610460, 623984, 630315, 636633, 654434, 668747, 670021, 673241, 676171, 692371, 699997, 706701, 712253, 713260, 723993, 729310, 730937, 731747, 752331, 764733, 771085, 771476, 780654, 788532, 794968, 795080, 795241, 796630, 796807, 807953, 809992, 812423, 815705, 819585, 819869, 823013,

In [174]:
###Save list of Missed Tackle Indices for 7 frames before
with open(folder_path + 'missed_indices_mt_07.pkl', 'wb') as f:
    pickle.dump(missing_indices_mt_07, f)

In [181]:
###Save list of Missed Tackle Indices for 10 frames before
with open(folder_path + 'missed_indices_mt_1.pkl', 'wb') as f:
    pickle.dump(missing_indices_mt_1, f)

In [165]:
'''OLD VERSION
###Function to delete rows where there is no data at least 7 frames before the tackle
def drop_dataless_rows(df, indices):
    count = 0
    for index in indices:
        game_play_id = df.loc[index, 'game_play_Id']
        nfl_id = df.loc[index, 'nflId']
        matching_rows = df[(df['game_play_Id'] == game_play_id) & (df['nflId'] == nfl_id)]
        count += len(matching_rows)
        df = df.drop(matching_rows.index)
    print(f'Total matching rows: {count}')
    return df
'''

In [204]:
###Function to delete rows where there is no data at least 10 frames before the tackle
def drop_dataless_rows(df, indices):
    count = 0
    for index in indices:
        if index in df.index:
            game_play_id = df.loc[index, 'game_play_Id']
            nfl_id = df.loc[index, 'nflId']
            matching_rows = df[(df['game_play_Id'] == game_play_id) & (df['nflId'] == nfl_id)]
            count += len(matching_rows)
            df = df.drop(matching_rows.index)
        else:
            print(f'Index {index} not in DataFrame')
    print(f'Total matching rows: {count}')
    return df

In [203]:
missing_indices_1

[1315,
 1327,
 2656,
 2670,
 14063,
 14074,
 17612,
 17623,
 17635,
 17647,
 18586,
 18600,
 20579,
 20590,
 21210,
 21223,
 28372,
 28385,
 33582,
 38659,
 38673,
 39329,
 39343,
 43404,
 43416,
 46962,
 46975,
 47234,
 47246,
 50191,
 50205,
 51887,
 51898,
 54749,
 54761,
 55128,
 55141,
 60335,
 60347,
 66088,
 66101,
 76756,
 76769,
 76851,
 76863,
 77770,
 77782,
 83988,
 84001,
 90209,
 90222,
 91263,
 91274,
 91562,
 91573,
 92539,
 92553,
 96571,
 96583,
 96964,
 96977,
 98068,
 98082,
 98508,
 98522,
 106329,
 106340,
 106353,
 106366,
 108474,
 108487,
 108500,
 119489,
 119500,
 121755,
 121769,
 122518,
 122532,
 127548,
 127562,
 136398,
 136409,
 138069,
 138083,
 139897,
 139911,
 140810,
 140822,
 142333,
 142347,
 144658,
 144669,
 144878,
 144889,
 154658,
 154669,
 154779,
 154791,
 156073,
 156087,
 156694,
 156707,
 159833,
 159845,
 163121,
 163133,
 170023,
 170036,
 175554,
 175568,
 179355,
 179369,
 180149,
 180161,
 189038,
 189052,
 191539,
 191550,
 196635

In [166]:
tracking_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1334038 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1334038 non-null  int64  
 1   playId            1334038 non-null  int64  
 2   nflId             1334038 non-null  float64
 3   displayName       1334038 non-null  object 
 4   frameId           1334038 non-null  int64  
 5   time              1334038 non-null  object 
 6   jerseyNumber      1334038 non-null  float64
 7   club              1334038 non-null  object 
 8   playDirection     1334038 non-null  object 
 9   x                 1334038 non-null  float64
 10  y                 1334038 non-null  float64
 11  s                 1334038 non-null  float64
 12  a                 1334038 non-null  float64
 13  dis               1334038 non-null  float64
 14  o                 1334038 non-null  float64
 15  dir               1334038 non-null  float64
 16  

In [167]:
###Running for Tackles Indices
tracking_clean_07 = drop_dataless_rows(tracking_clean, missing_indices_07)

Total matching rows: 1298


In [168]:
tracking_clean_07.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1332740 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1332740 non-null  int64  
 1   playId            1332740 non-null  int64  
 2   nflId             1332740 non-null  float64
 3   displayName       1332740 non-null  object 
 4   frameId           1332740 non-null  int64  
 5   time              1332740 non-null  object 
 6   jerseyNumber      1332740 non-null  float64
 7   club              1332740 non-null  object 
 8   playDirection     1332740 non-null  object 
 9   x                 1332740 non-null  float64
 10  y                 1332740 non-null  float64
 11  s                 1332740 non-null  float64
 12  a                 1332740 non-null  float64
 13  dis               1332740 non-null  float64
 14  o                 1332740 non-null  float64
 15  dir               1332740 non-null  float64
 16  event

In [169]:
###Running for Missed Tackle Indices
tracking_clean_07 = drop_dataless_rows(tracking_clean_07, missing_indices_mt_07)

Total matching rows: 3609


In [170]:
tracking_clean_07.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1329131 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1329131 non-null  int64  
 1   playId            1329131 non-null  int64  
 2   nflId             1329131 non-null  float64
 3   displayName       1329131 non-null  object 
 4   frameId           1329131 non-null  int64  
 5   time              1329131 non-null  object 
 6   jerseyNumber      1329131 non-null  float64
 7   club              1329131 non-null  object 
 8   playDirection     1329131 non-null  object 
 9   x                 1329131 non-null  float64
 10  y                 1329131 non-null  float64
 11  s                 1329131 non-null  float64
 12  a                 1329131 non-null  float64
 13  dis               1329131 non-null  float64
 14  o                 1329131 non-null  float64
 15  dir               1329131 non-null  float64
 16  event

In [182]:
tracking_clean_07.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_07.csv', index=False)

**Generating tracking_clean for observations that have at least 10 frames of data available before them**

In [189]:
# Convert the lists to sets
set_1 = set(missing_indices_1)
set_mt_1 = set(missing_indices_mt_1)

# Find the common elements
common_indices = set_1.intersection(set_mt_1)

# Convert the set back to a list, if needed
common_indices_list = list(common_indices)

print(common_indices_list)

[]


In [205]:
###Applying for Tackle Indices
tracking_clean_1 = drop_dataless_rows(tracking_clean, missing_indices_1)

Total matching rows: 8768


In [206]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1325270 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1325270 non-null  int64  
 1   playId            1325270 non-null  int64  
 2   nflId             1325270 non-null  float64
 3   displayName       1325270 non-null  object 
 4   frameId           1325270 non-null  int64  
 5   time              1325270 non-null  object 
 6   jerseyNumber      1325270 non-null  float64
 7   club              1325270 non-null  object 
 8   playDirection     1325270 non-null  object 
 9   x                 1325270 non-null  float64
 10  y                 1325270 non-null  float64
 11  s                 1325270 non-null  float64
 12  a                 1325270 non-null  float64
 13  dis               1325270 non-null  float64
 14  o                 1325270 non-null  float64
 15  dir               1325270 non-null  float64
 16  event

In [202]:
index_to_check = 311916
if index_to_check in missing_indices_1:
    print(f"Index {index_to_check} is in 'missing_indices_1'")
else:
    print(f"Index {index_to_check} is not in 'missing_indices_1'")


Index 311916 is in 'missing_indices_1'


In [207]:
###Applying for Missed Tackle Indices
tracking_clean_1 = drop_dataless_rows(tracking_clean_1, missing_indices_mt_1)

Index 311921 not in DataFrame
Total matching rows: 7394


In [208]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1317876 entries, 0 to 1334037
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1317876 non-null  int64  
 1   playId            1317876 non-null  int64  
 2   nflId             1317876 non-null  float64
 3   displayName       1317876 non-null  object 
 4   frameId           1317876 non-null  int64  
 5   time              1317876 non-null  object 
 6   jerseyNumber      1317876 non-null  float64
 7   club              1317876 non-null  object 
 8   playDirection     1317876 non-null  object 
 9   x                 1317876 non-null  float64
 10  y                 1317876 non-null  float64
 11  s                 1317876 non-null  float64
 12  a                 1317876 non-null  float64
 13  dis               1317876 non-null  float64
 14  o                 1317876 non-null  float64
 15  dir               1317876 non-null  float64
 16  event

In [209]:
tracking_clean_1.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_1.csv', index=False)

In [215]:
tracking_clean_1 = tracking_clean_1.reset_index(drop=True)

### **2.5: Deleting Observations from Tackles_1v1 which did not have a full second of data before hand**

In [232]:
def drop_matching_rows(df1, df2, indices):
    for i in indices:
        if i in df2.index:
            game_play_Id = df2.loc[i, 'game_play_Id']
            nflId = df2.loc[i, 'nflId']
            df1 = df1.drop(df1[(df1['game_play_Id'] == game_play_Id) & (df1['nflId'] == nflId)].index)
    return df1

In [246]:
tackles_1v1_1 = drop_matching_rows(tackles_1v1, tracking_clean, missing_indices_1)

In [247]:
tackles_1v1_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11667 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            11667 non-null  int64  
 1   playId            11667 non-null  int64  
 2   nflId             11667 non-null  int64  
 3   tackle            11667 non-null  int64  
 4   assist            11667 non-null  int64  
 5   forcedFumble      11667 non-null  int64  
 6   pff_missedTackle  11667 non-null  int64  
 7   game_play_Id      11667 non-null  object 
 8   event_type        11667 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 911.5+ KB


In [248]:
tackles_1v1_1 = drop_matching_rows(tackles_1v1_1, tracking_clean, missing_indices_mt_1)

In [249]:
tackles_1v1_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11472 entries, 0 to 9620
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            11472 non-null  int64  
 1   playId            11472 non-null  int64  
 2   nflId             11472 non-null  int64  
 3   tackle            11472 non-null  int64  
 4   assist            11472 non-null  int64  
 5   forcedFumble      11472 non-null  int64  
 6   pff_missedTackle  11472 non-null  int64  
 7   game_play_Id      11472 non-null  object 
 8   event_type        11472 non-null  float64
dtypes: float64(1), int64(7), object(1)
memory usage: 896.2+ KB


In [250]:
tackles_1v1_1.head(10)

gameId  playId  nflId  tackle  assist  forcedFumble  pff_missedTackle  \
0  2022090800     101  42816       1       0             0                 0   
1  2022090800     393  46232       1       0             0                 0   
2  2022090800     486  40166       1       0             0                 0   
3  2022090800     646  47939       1       0             0                 0   
4  2022090800     818  40107       1       0             0                 0   
5  2022090800    1286  44976       1       0             0                 0   
6  2022090800    1736  44976       1       0             0                 0   
7  2022090800    2860  46085       1       0             0                 0   
8  2022090800    3092  46190       1       0             0                 0   
9  2022090800    3145  52647       1       0             0                 0   

      game_play_Id  event_type  
0   2022090800_101         1.0  
1   2022090800_393         1.0  
2   2022090800_486         1.0  
3   2022090800_646         1.0  
4   2022090800_818         1.0  
5  2022090800_1286         1.0  
6  2022090800_1736         1.0  
7  2022090800_2860         1.0  
8  2022090800_3092         1.0  
9  2022090800_3145         1.0

### **2.6: Generating Average Magnitude**

In [251]:
def compute_speed_features_original(df1, df2):
    """
    Function to compute averages based on certain conditions and add them as new columns to df1.
    Different conditions are applied based on the value of df1['event_type'].

    Args:
    df1 (pd.DataFrame): Dataframe to iterate through.
    df2 (pd.DataFrame): Dataframe to find the index and calculate averages.

    Returns:
    pd.DataFrame: Updated df1 with new columns.
    """
    # Initialize the new columns in df1
    df1['s_avg_05'] = None
    df1['s_avg_1'] = None
    df1['bc_s_avg_05'] = None
    df1['bc_s_avg_1'] = None

    # Iterate through each row in df1
    for index, row in df1.iterrows():
        # Determine the condition based on df1['event_type']
        if row['event_type'] == 1:
            condition = (df2['event'] == 'tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 2:
            condition = (df2['new_event'] == 'missed tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 3:
            condition = (df2['event'] == 'fumble') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        else:
            continue  # Skip the row if the event_type is neither 1 nor 2

        matching_indexes = df2.index[condition]

        for i in matching_indexes:
            # Ensure index range does not go below 0
            start_index_05 = max(i - 5, 0)
            start_index_1 = max(i - 10, 0)

            # Calculate averages and assign to df1
            df1.at[index, 's_avg_05'] = df2.loc[start_index_05:i, 's'].mean()
            df1.at[index, 's_avg_1'] = df2.loc[start_index_1:start_index_05, 's'].mean()
            df1.at[index, 'bc_s_avg_05'] = df2.loc[start_index_05:i, 'bc_s'].mean()
            df1.at[index, 'bc_s_avg_1'] = df2.loc[start_index_1:start_index_05, 'bc_s'].mean()

    return df1

# Example usage:
# updated_df1 = compute_averages_modified(df1, df2)

In [252]:
tackles_1v1_1_test = compute_speed_features(tackles_1v1_1, tracking_clean_1)

In [261]:
tackles_1v1_1_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11472 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            11472 non-null  int64  
 1   playId            11472 non-null  int64  
 2   nflId             11472 non-null  int64  
 3   tackle            11472 non-null  int64  
 4   assist            11472 non-null  int64  
 5   forcedFumble      11472 non-null  int64  
 6   pff_missedTackle  11472 non-null  int64  
 7   game_play_Id      11472 non-null  object 
 8   event_type        11472 non-null  float64
 9   s_avg_05          9678 non-null   object 
 10  s_avg_1           9678 non-null   object 
 11  bc_s_avg_05       9678 non-null   object 
 12  bc_s_avg_1        9678 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.5+ MB


In [262]:
tracking_clean.event.value_counts()

event
first_contact                26142
tackle                       24948
ball_snap                    16053
handoff                      15071
pass_outcome_caught          12708
pass_arrived                 11123
out_of_bounds                 3924
run                           2140
man_in_motion                 1054
play_action                    652
touchdown                      545
shift                          359
qb_slide                       291
fumble                         244
pass_forward                   206
snap_direct                    127
lateral                         63
line_set                        56
pass_shovel                     38
autoevent_passforward           36
autoevent_passinterrupted       29
qb_sack                         21
autoevent_ballsnap              15
fumble_defense_recovered        14
penalty_flag                    12
fumble_offense_recovered         8
safety                           7
run_pass_option                  2
penalty_accept

**Exploration to find out why averages are not identified for all observations**

In [268]:
play_1 = tracking_clean_1.loc[(tracking_clean_1['game_play_Id'] == '2022090800_101') & (tracking_clean_1['nflId'] == 42816)]


In [275]:
play_1[39:44]

gameId  playId    nflId displayName  frameId  \
143  2022090800     101  42816.0   Troy Hill       40   
144  2022090800     101  42816.0   Troy Hill       41   
145  2022090800     101  42816.0   Troy Hill       42   
146  2022090800     101  42816.0   Troy Hill       43   
147  2022090800     101  42816.0   Troy Hill       44   

                           time  jerseyNumber club playDirection      x  \
143  2022-09-08 20:25:12.099999           2.0   LA          left  69.51   
144  2022-09-08 20:25:12.200000           2.0   LA          left  69.41   
145  2022-09-08 20:25:12.299999           2.0   LA          left  69.31   
146  2022-09-08 20:25:12.400000           2.0   LA          left  69.22   
147  2022-09-08 20:25:12.500000           2.0   LA          left  69.14   

         y     s     a   dis       o     dir event    game_play_Id  \
143  40.99  4.43  3.74  0.44  165.31  190.65   NaN  2022090800_101   
144  40.58  4.20  3.50  0.42  160.90  195.40   NaN  2022090800_101   
145  40.24  3.55  4.01  0.36  189.49  198.63   NaN  2022090800_101   
146  39.94  3.00  4.41  0.31  196.68  199.90   NaN  2022090800_101   
147  39.69  2.42  4.77  0.26  203.84  200.76   NaN  2022090800_101   

    defensiveTeam  ballCarrierId    bcx    bcy  bc_s  bc_a  bc_dis    bc_o  \
143            LA          47857  69.36  40.67  6.17  4.90    0.62  292.32   
144            LA          47857  68.76  40.63  5.97  4.68    0.60  293.95   
145            LA          47857  68.18  40.54  5.75  4.38    0.58  294.97   
146            LA          47857  67.65  40.43  5.47  4.04    0.54  296.60   
147            LA          47857  67.16  40.30  5.11  4.12    0.51  239.44   

     bc_dir  distance_from_bc  tackler_one  tackler_two  assister_one  \
143  270.68          0.353412      42816.0          NaN           NaN   
144  265.31          0.651920      42816.0          NaN           NaN   
145  260.48          1.169145      42816.0          NaN           NaN   
146  256.58          1.644688      42816.0          NaN           NaN   
147  253.43          2.071835      42816.0          NaN           NaN   

     assister_two  missed_tackler_1  missed_tackler_2  missed_tackler_3  \
143           NaN               NaN               NaN               NaN   
144           NaN               NaN               NaN               NaN   
145           NaN               NaN               NaN               NaN   
146           NaN               NaN               NaN               NaN   
147           NaN               NaN               NaN               NaN   

     missed_tackler_4  missed_tackler_5  missed_tackler_6 new_event    cosine  \
143               NaN               NaN               NaN       NaN  0.173133   
144               NaN               NaN               NaN       NaN  0.343496   
145               NaN               NaN               NaN       NaN  0.471782   
146               NaN               NaN               NaN       NaN  0.549315   
147               NaN               NaN               NaN       NaN  0.606405   

     do_align  bc_do_align  weight  bc_weight   force  bc_force  
143  0.718444     0.759556     184        203  688.16    994.70  
144  0.616667     0.681778     184        203  644.00    950.04  
145  0.898444     0.616778     184        203  737.84    889.14  
146  0.964222     0.555333     184        203  811.44    820.12  
147  0.965778     0.844556     184        203  877.68    836.36

In [276]:
play_1['s'][39:44].mean()

3.5200000000000005

In [254]:
tackles_1v1_1_test.head(50)

gameId  playId  nflId  tackle  assist  forcedFumble  pff_missedTackle  \
0   2022090800     101  42816       1       0             0                 0   
1   2022090800     393  46232       1       0             0                 0   
2   2022090800     486  40166       1       0             0                 0   
3   2022090800     646  47939       1       0             0                 0   
4   2022090800     818  40107       1       0             0                 0   
5   2022090800    1286  44976       1       0             0                 0   
6   2022090800    1736  44976       1       0             0                 0   
7   2022090800    2860  46085       1       0             0                 0   
8   2022090800    3092  46190       1       0             0                 0   
9   2022090800    3145  52647       1       0             0                 0   
10  2022090800    3362  46190       1       0             0                 0   
11  2022090800    3383  54488       1       0             0                 0   
12  2022091100    1260  44851       1       0             0                 0   
13  2022091100    1672  40017       1       0             0                 0   
14  2022091100    2114  53469       1       0             0                 0   
15  2022091100    2353  38607       1       0             0                 0   
16  2022091100    2512  53611       1       0             0                 0   
17  2022091100    2640  44862       1       0             0                 0   
18  2022091100    2878  53489       1       0             0                 0   
19  2022091100    2899  37097       1       0             0                 0   
20  2022091100    3578  52542       1       0             0                 0   
21  2022091100    3647  53469       1       0             0                 0   
22  2022091100    3778  53489       1       0             0                 0   
23  2022091101    1691  53481       1       0             0                 0   
24  2022091101    1744  44903       1       0             0                 0   
25  2022091101    1785  52452       1       0             0                 0   
26  2022091101    2051  46527       1       0             0                 0   
27  2022091101    3221  47799       1       0             0                 0   
28  2022091102      86  44938       1       0             0                 0   
29  2022091102     531  52571       1       0             0                 0   
30  2022091102     756  53609       1       0             0                 0   
31  2022091102    1493  54504       1       0             0                 0   
32  2022091102    2065  54504       1       0             0                 0   
33  2022091102    2352  46290       1       0             0                 0   
34  2022091102    2759  54504       1       0             0                 0   
35  2022091102    3783  52571       1       0             0                 0   
36  2022091102    4102  54639       1       0             0                 0   
37  2022091103     520  46146       1       0             0                 0   
38  2022091103    1037  44842       1       0             0                 0   
39  2022091103    1315  46080       1       0             0                 0   
40  2022091103    1405  46080       1       0             0                 0   
41  2022091103    1672  46080       1       0             0                 0   
42  2022091103    2058  43641       1       0             0                 0   
43  2022091103    2172  46097       1       0             0                 0   
44  2022091103    2222  44842       1       0             0                 0   
45  2022091103    2291  46698       1       0             0                 0   
47  2022091103    3147  44872       1       0             0                 0   
48  2022091103    3251  43325       1       0             0                 0   
49  2022091103    4175  43641       1  

In [286]:
def count_and_delete_out_of_bounds(tackles_1v1_1_test, tracking_clean_1):
    # Filter rows where 's_avg_05', 's_avg_1', 'bc_s_avg_05', and 'bc_s_avg_1' are None
    filtered_tackles = tackles_1v1_1_test[tackles_1v1_1_test[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

    count = 0
    # Iterate over the filtered rows
    for index, row in filtered_tackles.iterrows():
        # Find matching rows in tracking_clean_1
        matching_rows = tracking_clean_1[(tracking_clean_1['game_play_Id'] == row['game_play_Id']) & 
                                         (tracking_clean_1['nflId'] == row['nflId'])]
        # Count how many times 'event' is 'out_of_bounds'
        count += (matching_rows['event'] == 'out_of_bounds').sum()
        
        # Drop the row from tackles_1v1_1_test if it contributes to the count
        if (matching_rows['event'] == 'out_of_bounds').sum() > 0:
            tackles_1v1_1_test = tackles_1v1_1_test.drop(index)
    
    return tackles_1v1_1_test


In [287]:
tackles_1v1_1_test_drop = count_and_delete_out_of_bounds(tackles_1v1_1_test, tracking_clean_1)

In [285]:
tackles_1v1_1_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11472 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            11472 non-null  int64  
 1   playId            11472 non-null  int64  
 2   nflId             11472 non-null  int64  
 3   tackle            11472 non-null  int64  
 4   assist            11472 non-null  int64  
 5   forcedFumble      11472 non-null  int64  
 6   pff_missedTackle  11472 non-null  int64  
 7   game_play_Id      11472 non-null  object 
 8   event_type        11472 non-null  float64
 9   s_avg_05          9678 non-null   object 
 10  s_avg_1           9678 non-null   object 
 11  bc_s_avg_05       9678 non-null   object 
 12  bc_s_avg_1        9678 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.5+ MB


In [288]:
tackles_1v1_1_test_drop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9875 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9875 non-null   int64  
 1   playId            9875 non-null   int64  
 2   nflId             9875 non-null   int64  
 3   tackle            9875 non-null   int64  
 4   assist            9875 non-null   int64  
 5   forcedFumble      9875 non-null   int64  
 6   pff_missedTackle  9875 non-null   int64  
 7   game_play_Id      9875 non-null   object 
 8   event_type        9875 non-null   float64
 9   s_avg_05          9678 non-null   object 
 10  s_avg_1           9678 non-null   object 
 11  bc_s_avg_05       9678 non-null   object 
 12  bc_s_avg_1        9678 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.1+ MB


**Seeing why remaining 197 are missing**

In [316]:
tracking_clean_1.loc[(tracking_clean_1['game_play_Id'] == '2022092513_2900') & (tracking_clean_1['nflId'] == 46757)]

gameId  playId    nflId      displayName  frameId  \
443112  2022092513    2900  46757.0  Charvarius Ward        1   
443113  2022092513    2900  46757.0  Charvarius Ward        2   
443114  2022092513    2900  46757.0  Charvarius Ward        3   
443115  2022092513    2900  46757.0  Charvarius Ward        4   
443116  2022092513    2900  46757.0  Charvarius Ward        5   
443117  2022092513    2900  46757.0  Charvarius Ward        6   
443118  2022092513    2900  46757.0  Charvarius Ward        7   
443119  2022092513    2900  46757.0  Charvarius Ward        8   
443120  2022092513    2900  46757.0  Charvarius Ward        9   
443121  2022092513    2900  46757.0  Charvarius Ward       10   
443122  2022092513    2900  46757.0  Charvarius Ward       11   
443123  2022092513    2900  46757.0  Charvarius Ward       12   
443124  2022092513    2900  46757.0  Charvarius Ward       13   
443125  2022092513    2900  46757.0  Charvarius Ward       14   
443126  2022092513    2900  46757.0  Charvarius Ward       15   
443127  2022092513    2900  46757.0  Charvarius Ward       16   
443128  2022092513    2900  46757.0  Charvarius Ward       17   
443129  2022092513    2900  46757.0  Charvarius Ward       18   
443130  2022092513    2900  46757.0  Charvarius Ward       19   
443131  2022092513    2900  46757.0  Charvarius Ward       20   
443132  2022092513    2900  46757.0  Charvarius Ward       21   
443133  2022092513    2900  46757.0  Charvarius Ward       22   
443134  2022092513    2900  46757.0  Charvarius Ward       23   
443135  2022092513    2900  46757.0  Charvarius Ward       24   
443136  2022092513    2900  46757.0  Charvarius Ward       25   
443137  2022092513    2900  46757.0  Charvarius Ward       26   
443138  2022092513    2900  46757.0  Charvarius Ward       27   
443139  2022092513    2900  46757.0  Charvarius Ward       28   
443140  2022092513    2900  46757.0  Charvarius Ward       29   
443141  2022092513    2900  46757.0  Charvarius Ward       30   
443142  2022092513    2900  46757.0  Charvarius Ward       31   
443143  2022092513    2900  46757.0  Charvarius Ward       32   
443144  2022092513    2900  46757.0  Charvarius Ward       33   
443145  2022092513    2900  46757.0  Charvarius Ward       34   
443146  2022092513    2900  46757.0  Charvarius Ward       35   
443147  2022092513    2900  46757.0  Charvarius Ward       36   
443148  2022092513    2900  46757.0  Charvarius Ward       37   
443149  2022092513    2900  46757.0  Charvarius Ward       38   
443150  2022092513    2900  46757.0  Charvarius Ward       39   
443151  2022092513    2900  46757.0  Charvarius Ward       40   
443152  2022092513    2900  46757.0  Charvarius Ward       41   
443153  2022092513    2900  46757.0  Charvarius Ward       42   
443154  2022092513    2900  46757.0  Charvarius Ward       43   
443155  2022092513    2900  46757.0  Charvarius Ward       44   
443156  2022092513    2900  46757.0  Charvarius Ward       45   
443157  2022092513    2900  46757.0  Charvarius Ward       46   
443158  2022092513    2900  46757.0  Charvarius Ward       47   
443159  2022092513    2900  46757.0  Charvarius Ward       48   
443160  2022092513    2900  46757.0  Charvarius Ward       49   
443161  2022092513    2900  46757.0  Charvarius Ward       50   
443162  2022092513    2900  46757.0  Charvarius Ward       51   
443163  2022092513    2900  46757.0  Charvarius Ward       52   
443164  2022092513    2900  46757.0  Charvarius Ward       53   
443165  2022092513    2900  46757.0  Charvarius Ward       54   

                              time  jerseyNumber club playDirection      x  \
443112  2022-09-25 22:41:58.400000           7.0   SF         right  17.73   
443113  2022-09-25 22:41:58.500000           7.0   SF         right  17.70   
443114  2022-09-25 22:41:58.599999           7.0   SF         right  17.67   
443115  2022-09-25 22:41:58.700000           7.0   SF         right  17.66   
443116  2022-09-25 22:41:58.799999           7

In [305]:
missing_197_events = tackles_1v1_1_test_drop[tackles_1v1_1_test_drop[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]


In [321]:
missing_197_events.forcedFumble.value_counts()

forcedFumble
0    134
1     63
Name: count, dtype: int64

**Dropping observations with missing generated speed features where tackler did not force fumble**

In [322]:
# Create a mask for rows where all specified columns are null
null_mask = tackles_1v1_1_test_drop[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)

# Create a mask for rows where 'tackle' is 1 and 'forcedFumble' is not 1
tackle_mask = (tackles_1v1_1_test_drop['tackle'] == 1) & (tackles_1v1_1_test_drop['forcedFumble'] != 1)

# Combine the masks and drop the rows
tackles_1v1_1_fumbles = tackles_1v1_1_test_drop.drop(tackles_1v1_1_test_drop[null_mask & tackle_mask].index)

In [330]:
tackles_1v1_1_fumbles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9741 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9741 non-null   int64  
 1   playId            9741 non-null   int64  
 2   nflId             9741 non-null   int64  
 3   tackle            9741 non-null   int64  
 4   assist            9741 non-null   int64  
 5   forcedFumble      9741 non-null   int64  
 6   pff_missedTackle  9741 non-null   int64  
 7   game_play_Id      9741 non-null   object 
 8   event_type        9741 non-null   float64
 9   s_avg_05          9678 non-null   object 
 10  s_avg_1           9678 non-null   object 
 11  bc_s_avg_05       9678 non-null   object 
 12  bc_s_avg_1        9678 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB


In [333]:
all_71_fumbles = tackles_1v1_1_fumbles[tackles_1v1_1_fumbles.forcedFumble == 1]

In [360]:
long_play = tracking_clean_1.loc[(tracking_clean_1['game_play_Id'] == '2022100904_3777') & (tracking_clean_1['nflId'] == 52497)]

In [361]:
long_play[:60]

gameId  playId    nflId       displayName  frameId  \
667593  2022100904    3777  52497.0  Cameron Dantzler        1   
667594  2022100904    3777  52497.0  Cameron Dantzler        2   
667595  2022100904    3777  52497.0  Cameron Dantzler        3   
667596  2022100904    3777  52497.0  Cameron Dantzler        4   
667597  2022100904    3777  52497.0  Cameron Dantzler        5   
667598  2022100904    3777  52497.0  Cameron Dantzler        6   
667599  2022100904    3777  52497.0  Cameron Dantzler        7   
667600  2022100904    3777  52497.0  Cameron Dantzler        8   
667601  2022100904    3777  52497.0  Cameron Dantzler        9   
667602  2022100904    3777  52497.0  Cameron Dantzler       10   
667603  2022100904    3777  52497.0  Cameron Dantzler       11   
667604  2022100904    3777  52497.0  Cameron Dantzler       12   
667605  2022100904    3777  52497.0  Cameron Dantzler       13   
667606  2022100904    3777  52497.0  Cameron Dantzler       14   
667607  2022100904    3777  52497.0  Cameron Dantzler       15   
667608  2022100904    3777  52497.0  Cameron Dantzler       16   
667609  2022100904    3777  52497.0  Cameron Dantzler       17   
667610  2022100904    3777  52497.0  Cameron Dantzler       18   
667611  2022100904    3777  52497.0  Cameron Dantzler       19   
667612  2022100904    3777  52497.0  Cameron Dantzler       20   
667613  2022100904    3777  52497.0  Cameron Dantzler       21   
667614  2022100904    3777  52497.0  Cameron Dantzler       22   
667615  2022100904    3777  52497.0  Cameron Dantzler       23   
667616  2022100904    3777  52497.0  Cameron Dantzler       24   
667617  2022100904    3777  52497.0  Cameron Dantzler       25   
667618  2022100904    3777  52497.0  Cameron Dantzler       26   
667619  2022100904    3777  52497.0  Cameron Dantzler       27   
667620  2022100904    3777  52497.0  Cameron Dantzler       28   
667621  2022100904    3777  52497.0  Cameron Dantzler       29   
667622  2022100904    3777  52497.0  Cameron Dantzler       30   
667623  2022100904    3777  52497.0  Cameron Dantzler       31   
667624  2022100904    3777  52497.0  Cameron Dantzler       32   
667625  2022100904    3777  52497.0  Cameron Dantzler       33   
667626  2022100904    3777  52497.0  Cameron Dantzler       34   
667627  2022100904    3777  52497.0  Cameron Dantzler       35   
667628  2022100904    3777  52497.0  Cameron Dantzler       36   
667629  2022100904    3777  52497.0  Cameron Dantzler       37   
667630  2022100904    3777  52497.0  Cameron Dantzler       38   
667631  2022100904    3777  52497.0  Cameron Dantzler       39   
667632  2022100904    3777  52497.0  Cameron Dantzler       40   
667633  2022100904    3777  52497.0  Cameron Dantzler       41   

                              time  jerseyNumber club playDirection      x  \
667593  2022-10-09 15:50:01.400000           3.0  MIN          left  51.24   
667594  2022-10-09 15:50:01.500000           3.0  MIN          left  51.49   
667595  2022-10-09 15:50:01.599999           3.0  MIN          left  51.77   
667596  2022-10-09 15:50:01.700000           3.0  MIN          left  52.06   
667597  2022-10-09 15:50:01.799999           3.0  MIN          left  52.36   
667598  2022-10-09 15:50:01.900000           3.0  MIN          left  52.68   
667599  2022-10-09 15:50:02.000000           3.0  MIN          left  52.98   
667600  2022-10-09 15:50:02.099999           3.0  MIN          left  53.25   
667601  2022-10-09 15:50:02.200000           3.0  MIN          left  53.51   
667602  2022-10-09 15:50:02.299999           3.0  MIN          left  53.74   
667603  2022-10-09 15:50:02.400000           3.0  MIN          left  53.93   
667604  2022-10-09 15:50:02.500000           3.0  MIN          left  54.10   
667605  2022-10-09 15:50:02.599999           3.0  MIN          left  54.23   
667606  2022-10-09 15:50:02.700000           3.0  MIN          left  54.33   
667607  2022-10-09 15:50:02.799999           3.0  MIN          left  

In [359]:
all_71_fumbles[59:]

gameId  playId  nflId  tackle  assist  forcedFumble  \
7887  2022110608    1940  46711       1       0             1   
8090  2022110300    3506  54540       1       0             1   
8123  2022110603    3713  52411       1       0             1   
8374  2022110600    2183  41231       1       0             1   
8689  2022103009    2259  53592       1       0             1   
8913  2022100208    3298  54504       1       0             1   
9135  2022101600     690  54503       1       0             1   
9284  2022102303     193  47996       1       0             1   
9311  2022102305    3425  41483       1       0             1   
9496  2022103012     762  54487       1       0             1   
9557  2022110603    3689  46958       1       0             1   
4647  2022100904    3777  52497       1       0             1   

      pff_missedTackle     game_play_Id  event_type  s_avg_05   s_avg_1  \
7887                 0  2022110608_1940         1.0      None      None   
8090                 0  2022110300_3506         1.0  5.051667  6.453333   
8123                 0  2022110603_3713         1.0      None      None   
8374                 0  2022110600_2183         1.0      None      None   
8689                 0  2022103009_2259         1.0      None      None   
8913                 0  2022100208_3298         1.0  1.866667  1.473333   
9135                 0   2022101600_690         1.0      None      None   
9284                 0   2022102303_193         1.0      None      None   
9311                 0  2022102305_3425         1.0      None      None   
9496                 0   2022103012_762         1.0      None      None   
9557                 0  2022110603_3689         1.0      None      None   
4647                 0  2022100904_3777         1.0      2.97  3.363333   

     bc_s_avg_05 bc_s_avg_1  
7887        None       None  
8090    5.248333      5.825  
8123        None       None  
8374        None       None  
8689        None       None  
8913       2.785   5.581667  
9135        None       None  
9284        None       None  
9311        None       None  
9496        None       None  
9557        None       None  
4647    2.683333   2.796667

In [373]:
fumbles_63 = tackles_1v1_1_fumbles[tackles_1v1_1_fumbles[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

In [374]:
fumbles_63.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63 entries, 81 to 9557
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            63 non-null     int64  
 1   playId            63 non-null     int64  
 2   nflId             63 non-null     int64  
 3   tackle            63 non-null     int64  
 4   assist            63 non-null     int64  
 5   forcedFumble      63 non-null     int64  
 6   pff_missedTackle  63 non-null     int64  
 7   game_play_Id      63 non-null     object 
 8   event_type        63 non-null     float64
 9   s_avg_05          0 non-null      object 
 10  s_avg_1           0 non-null      object 
 11  bc_s_avg_05       0 non-null      object 
 12  bc_s_avg_1        0 non-null      object 
dtypes: float64(1), int64(7), object(5)
memory usage: 6.9+ KB


In [372]:
tracking_clean_1.loc[(tracking_clean_1['game_play_Id'] == '2022102300_3733') & (tracking_clean_1['nflId'] == 52627)]

gameId  playId    nflId displayName  frameId  \
921449  2022102300    3733  52627.0  Geno Stone        1   
921450  2022102300    3733  52627.0  Geno Stone        2   
921451  2022102300    3733  52627.0  Geno Stone        3   
921452  2022102300    3733  52627.0  Geno Stone        4   
921453  2022102300    3733  52627.0  Geno Stone        5   
921454  2022102300    3733  52627.0  Geno Stone        6   
921455  2022102300    3733  52627.0  Geno Stone        7   
921456  2022102300    3733  52627.0  Geno Stone        8   
921457  2022102300    3733  52627.0  Geno Stone        9   
921458  2022102300    3733  52627.0  Geno Stone       10   
921459  2022102300    3733  52627.0  Geno Stone       11   
921460  2022102300    3733  52627.0  Geno Stone       12   
921461  2022102300    3733  52627.0  Geno Stone       13   
921462  2022102300    3733  52627.0  Geno Stone       14   
921463  2022102300    3733  52627.0  Geno Stone       15   
921464  2022102300    3733  52627.0  Geno Stone       16   
921465  2022102300    3733  52627.0  Geno Stone       17   
921466  2022102300    3733  52627.0  Geno Stone       18   
921467  2022102300    3733  52627.0  Geno Stone       19   
921468  2022102300    3733  52627.0  Geno Stone       20   
921469  2022102300    3733  52627.0  Geno Stone       21   
921470  2022102300    3733  52627.0  Geno Stone       22   

                              time  jerseyNumber club playDirection      x  \
921449  2022-10-23 15:57:22.200000          26.0  BAL          left  72.27   
921450  2022-10-23 15:57:22.299999          26.0  BAL          left  71.93   
921451  2022-10-23 15:57:22.400000          26.0  BAL          left  71.59   
921452  2022-10-23 15:57:22.500000          26.0  BAL          left  71.26   
921453  2022-10-23 15:57:22.599999          26.0  BAL          left  70.96   
921454  2022-10-23 15:57:22.700000          26.0  BAL          left  70.67   
921455  2022-10-23 15:57:22.799999          26.0  BAL          left  70.43   
921456  2022-10-23 15:57:22.900000          26.0  BAL          left  70.22   
921457  2022-10-23 15:57:23.000000          26.0  BAL          left  70.04   
921458  2022-10-23 15:57:23.099999          26.0  BAL          left  69.90   
921459  2022-10-23 15:57:23.200000          26.0  BAL          left  69.77   
921460  2022-10-23 15:57:23.299999          26.0  BAL          left  69.66   
921461  2022-10-23 15:57:23.400000          26.0  BAL          left  69.54   
921462  2022-10-23 15:57:23.500000          26.0  BAL          left  69.42   
921463  2022-10-23 15:57:23.599999          26.0  BAL          left  69.30   
921464  2022-10-23 15:57:23.700000          26.0  BAL          left  69.16   
921465  2022-10-23 15:57:23.799999          26.0  BAL          left  68.99   
921466  2022-10-23 15:57:23.900000          26.0  BAL          left  68.80   
921467  2022-10-23 15:57:24.000000          26.0  BAL          left  68.61   
921468  2022-10-23 15:57:24.099999          26.0  BAL          left  68.40   
921469  2022-10-23 15:57:24.200000          26.0  BAL          left  68.19   
921470  2022-10-23 15:57:24.299999          26.0  BAL          left  67.97   

            y     s     a   dis       o     dir                event  \
921449  45.84  4.25  3.52  0.41  194.61  233.59                  NaN   
921450  45.57  4.52  3.10  0.44  194.61  230.39                  NaN   
921451  45.25  4.77  3.03  0.47  197.14  225.39                  NaN   
921452  44.89  4.94  2.92  0.49  196.22  220.80                  NaN   
921453  44.49  5.13  3.12  0.51  194.79  215.65         pass_arrived   
921454  44.05  5.26  2.87  0.52  198.12  212.14  pass_outcome_caught   
921455  43.58  5.36  3.33  0.53  200.71  205.99                  NaN   
921456  43.06  5.57  3.74  0.56  199.23  201.07                  NaN   
921457  42.51  5.82  3.79  0.58  191.50  196.21                  NaN   
921458  41.93  6.06  3.43  0.60  190.61  192.66                  NaN   
921459  41.32  6.25  2.77  0.62  188.81  190

In [328]:
fumbles_63[:60]

gameId  playId  nflId  tackle  assist  forcedFumble  \
81    2022091106    3213  54936       1       0             1   
208   2022091805     327  52518       1       0             1   
269   2022091103    2740  44872       1       0             1   
439   2022091100     679  53489       1       0             1   
528   2022091110    1695  43326       1       0             1   
731   2022091110    3842  52539       1       0             1   
806   2022091801    3557  53481       1       0             1   
912   2022091107    2680  46211       1       0             1   
952   2022091111    2360  47843       1       0             1   
1208  2022091200    2712  46117       1       0             1   
1297  2022091102     268  52458       1       0             1   
1357  2022091107    2987  44999       1       0             1   
1364  2022091109    2083  53592       1       0             1   
1372  2022091110    1868  46657       1       0             1   
1404  2022091108    3366  52469       1       0             1   
1672  2022092513    2900  46757       1       0             1   
1840  2022092505    3069  43700       1       0             1   
1982  2022092200    1419  44903       1       0             1   
2112  2022092513    3504  54637       1       0             1   
2131  2022091807    3338  53537       1       0             1   
2293  2022092512    1985  48241       1       0             1   
2392  2022092501     684  44925       1       0             1   
2481  2022092510    3485  44848       1       0             1   
2596  2022091811    4519  52416       1       0             1   
2639  2022092500     586  46527       1       0             1   
2684  2022092505    3437  54479       1       0             1   
2685  2022092505    3740  42361       1       0             1   
3531  2022091200    1092  42393       1       0             1   
3534  2022091200    2292  42543       1       0             1   
3617  2022100202     881  53460       1       0             1   
3633  2022100204    4070  43478       1       0             1   
3831  2022100201     676  52542       1       0             1   
3943  2022100600    1335  53438       1       0             1   
4317  2022100207    3117  43388       1       0             1   
5003  2022101609    2732  54574       1       0             1   
5173  2022101604    2636  46307       1       0             1   
5258  2022102300    3733  52627       1       0             1   
5326  2022101000    1667  52546       1       0             1   
5468  2022102300    3248  53481       1       0             1   
5496  2022102304    1759  52444       1       0             1   
5559  2022100910     467  42470       1       0             1   
5921  2022092513    3925  48447       1       0             1   
5980  2022100205    1570  54574       1       0             1   
6014  2022100209     617  53663       1       0             1   
6168  2022102303    1658  54562       1       0             1   
6295  2022103002    2935  46088       1       0             1   
6433  2022103001    2496  43441       1       0             1   
6531  2022103011    1465  44830       1       0             1   
7100  2022103003     395  54562       1       0             1   
7308  2022110605    2150  47872       1       0             1   
7459  2022102309     182  52435       1       0             1   
7715  2022101603    1589  53462       1       0             1   
7731  2022101604    3589  38559       1       0             1   
7856  2022110605    3394  52619       1       0             1   
7887  2022110608    1940  46711       1       0             1   
8123  2022110603    3713  52411       1       0             1   
8374  2022110600    2183  41231       1       0             1   
8689  2022103009    2259  53592       1       0             1   
9135  2022101600     690  54503       1       0             1   
9284  2022102303     193  47996       1       0             1   

      pff_missedTackle     game_play_Id  eve

**Manipulating observations that had fumbles recorded but also tackle or missed tackles**

In [364]:
tackles_1v1_1_fumbles = tackles_1v1_1_fumbles[tackles_1v1_1_fumbles['game_play_Id'] != '2022100904_3777']


In [369]:
tackles_1v1_1_fumbles.loc[tackles_1v1_1_fumbles['game_play_Id'] == '2022091109_1827', 'event_type'] = 3
tackles_1v1_1_fumbles[tackles_1v1_1_fumbles['game_play_Id'] == '2022091109_1827']

gameId  playId  nflId  tackle  assist  forcedFumble  \
1140  2022091109    1827  47790       1       0             1   

      pff_missedTackle     game_play_Id  event_type  s_avg_05   s_avg_1  \
1140                 0  2022091109_1827         3.0  1.468333  1.576667   

     bc_s_avg_05 bc_s_avg_1  
1140    3.671667   4.611667

In [377]:
tackles_1v1_1_fumbles.event_type.value_counts()

event_type
1.0    7784
2.0    1891
3.0      64
Name: count, dtype: int64

In [376]:
tackles_1v1_1_fumbles.loc[tackles_1v1_1_fumbles[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1), 'event_type'] = 3
tackles_1v1_1_fumbles[tackles_1v1_1_fumbles[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

gameId  playId  nflId  tackle  assist  forcedFumble  \
81    2022091106    3213  54936       1       0             1   
208   2022091805     327  52518       1       0             1   
269   2022091103    2740  44872       1       0             1   
439   2022091100     679  53489       1       0             1   
528   2022091110    1695  43326       1       0             1   
...          ...     ...    ...     ...     ...           ...   
9135  2022101600     690  54503       1       0             1   
9284  2022102303     193  47996       1       0             1   
9311  2022102305    3425  41483       1       0             1   
9496  2022103012     762  54487       1       0             1   
9557  2022110603    3689  46958       1       0             1   

      pff_missedTackle     game_play_Id  event_type s_avg_05 s_avg_1  \
81                   0  2022091106_3213         3.0     None    None   
208                  0   2022091805_327         3.0     None    None   
269                  0  2022091103_2740         3.0     None    None   
439                  0   2022091100_679         3.0     None    None   
528                  0  2022091110_1695         3.0     None    None   
...                ...              ...         ...      ...     ...   
9135                 0   2022101600_690         3.0     None    None   
9284                 0   2022102303_193         3.0     None    None   
9311                 0  2022102305_3425         3.0     None    None   
9496                 0   2022103012_762         3.0     None    None   
9557                 0  2022110603_3689         3.0     None    None   

     bc_s_avg_05 bc_s_avg_1  
81          None       None  
208         None       None  
269         None       None  
439         None       None  
528         None       None  
...          ...        ...  
9135        None       None  
9284        None       None  
9311        None       None  
9496        None       None  
9557        None       None  

[63 rows x 13 columns]

In [386]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1317876 entries, 0 to 1317875
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1317876 non-null  int64  
 1   playId            1317876 non-null  int64  
 2   nflId             1317876 non-null  float64
 3   displayName       1317876 non-null  object 
 4   frameId           1317876 non-null  int64  
 5   time              1317876 non-null  object 
 6   jerseyNumber      1317876 non-null  float64
 7   club              1317876 non-null  object 
 8   playDirection     1317876 non-null  object 
 9   x                 1317876 non-null  float64
 10  y                 1317876 non-null  float64
 11  s                 1317876 non-null  float64
 12  a                 1317876 non-null  float64
 13  dis               1317876 non-null  float64
 14  o                 1317876 non-null  float64
 15  dir               1317876 non-null  float64
 16  

In [388]:
###Dropping Fumble Rows without at least a second of data before the fumble from the tracking data
tracking_clean_1 = drop_dataless_rows(tracking_clean_1, missing_indices_fumble_1)

Total matching rows: 53


In [389]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1317823 entries, 0 to 1317875
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1317823 non-null  int64  
 1   playId            1317823 non-null  int64  
 2   nflId             1317823 non-null  float64
 3   displayName       1317823 non-null  object 
 4   frameId           1317823 non-null  int64  
 5   time              1317823 non-null  object 
 6   jerseyNumber      1317823 non-null  float64
 7   club              1317823 non-null  object 
 8   playDirection     1317823 non-null  object 
 9   x                 1317823 non-null  float64
 10  y                 1317823 non-null  float64
 11  s                 1317823 non-null  float64
 12  a                 1317823 non-null  float64
 13  dis               1317823 non-null  float64
 14  o                 1317823 non-null  float64
 15  dir               1317823 non-null  float64
 16  event

In [390]:
tracking_clean_1 = tracking_clean_1.reset_index(drop=True)

In [391]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1317823 entries, 0 to 1317822
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1317823 non-null  int64  
 1   playId            1317823 non-null  int64  
 2   nflId             1317823 non-null  float64
 3   displayName       1317823 non-null  object 
 4   frameId           1317823 non-null  int64  
 5   time              1317823 non-null  object 
 6   jerseyNumber      1317823 non-null  float64
 7   club              1317823 non-null  object 
 8   playDirection     1317823 non-null  object 
 9   x                 1317823 non-null  float64
 10  y                 1317823 non-null  float64
 11  s                 1317823 non-null  float64
 12  a                 1317823 non-null  float64
 13  dis               1317823 non-null  float64
 14  o                 1317823 non-null  float64
 15  dir               1317823 non-null  float64
 16  

In [392]:
tracking_clean_1.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_1.csv', index=False)

In [393]:
tracking_clean_1_old = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tracking_clean_1.csv')

In [394]:
tracking_clean_1_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1317876 entries, 0 to 1317875
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1317876 non-null  int64  
 1   playId            1317876 non-null  int64  
 2   nflId             1317876 non-null  float64
 3   displayName       1317876 non-null  object 
 4   frameId           1317876 non-null  int64  
 5   time              1317876 non-null  object 
 6   jerseyNumber      1317876 non-null  float64
 7   club              1317876 non-null  object 
 8   playDirection     1317876 non-null  object 
 9   x                 1317876 non-null  float64
 10  y                 1317876 non-null  float64
 11  s                 1317876 non-null  float64
 12  a                 1317876 non-null  float64
 13  dis               1317876 non-null  float64
 14  o                 1317876 non-null  float64
 15  dir               1317876 non-null  float64
 16  

In [395]:
tackles_1v1_1_fumbles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9739 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9739 non-null   int64  
 1   playId            9739 non-null   int64  
 2   nflId             9739 non-null   int64  
 3   tackle            9739 non-null   int64  
 4   assist            9739 non-null   int64  
 5   forcedFumble      9739 non-null   int64  
 6   pff_missedTackle  9739 non-null   int64  
 7   game_play_Id      9739 non-null   object 
 8   event_type        9739 non-null   float64
 9   s_avg_05          9676 non-null   object 
 10  s_avg_1           9676 non-null   object 
 11  bc_s_avg_05       9676 non-null   object 
 12  bc_s_avg_1        9676 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB


In [396]:
###Dropping tackling events with fumble and not at least 4 seconds of data before the fumble from the tracking data
tackles_1v1_1_master = drop_matching_rows(tackles_1v1_1_fumbles, tracking_clean_1_old, missing_indices_fumble_1)

In [397]:
tackles_1v1_1_master.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9735 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9735 non-null   int64  
 1   playId            9735 non-null   int64  
 2   nflId             9735 non-null   int64  
 3   tackle            9735 non-null   int64  
 4   assist            9735 non-null   int64  
 5   forcedFumble      9735 non-null   int64  
 6   pff_missedTackle  9735 non-null   int64  
 7   game_play_Id      9735 non-null   object 
 8   event_type        9735 non-null   float64
 9   s_avg_05          9676 non-null   object 
 10  s_avg_1           9676 non-null   object 
 11  bc_s_avg_05       9676 non-null   object 
 12  bc_s_avg_1        9676 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB


In [401]:
tracking_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1317823 entries, 0 to 1317822
Data columns (total 46 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   gameId            1317823 non-null  int64  
 1   playId            1317823 non-null  int64  
 2   nflId             1317823 non-null  float64
 3   displayName       1317823 non-null  object 
 4   frameId           1317823 non-null  int64  
 5   time              1317823 non-null  object 
 6   jerseyNumber      1317823 non-null  float64
 7   club              1317823 non-null  object 
 8   playDirection     1317823 non-null  object 
 9   x                 1317823 non-null  float64
 10  y                 1317823 non-null  float64
 11  s                 1317823 non-null  float64
 12  a                 1317823 non-null  float64
 13  dis               1317823 non-null  float64
 14  o                 1317823 non-null  float64
 15  dir               1317823 non-null  float64
 16  

---

**Updated Compute Speed**

In [699]:
def compute_speed_features(df1, df2):
    """
    Function to compute averages based on certain conditions and add them as new columns to df1.
    Different conditions are applied based on the value of df1['event_type'].

    Args:
    df1 (pd.DataFrame): Dataframe to iterate through.
    df2 (pd.DataFrame): Dataframe to find the index and calculate averages.

    Returns:
    pd.DataFrame: Updated df1 with new columns.
    """
    # Initialize the new columns in df1
    df1['s_avg_05'] = None
    df1['s_avg_1'] = None
    df1['bc_s_avg_05'] = None
    df1['bc_s_avg_1'] = None

    # Iterate through each row in df1
    for index, row in df1.iterrows():
        # Print the index if it is a multiple of 1000
        if index % 1000 == 0:
            print(f"Processing index: {index}")
            
        # Determine the condition based on df1['event_type']
        if row['event_type'] == 1:
            condition = (df2['event'] == 'tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 2:
            condition = (df2['new_event'] == 'missed tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 3:
            condition = (df2['event'] == 'fumble') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 4:
            condition = (df2['event'] == 'first_contact') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        else:
            continue  # Skip the row if the event_type is neither 1,2,3, nor 4

        matching_indexes = df2.index[condition]

        #Checking if there are no matching indexes
        if len(matching_indexes) == 0:
            print(f"Index {index} has no matching index")
            continue
        #Checking if there is one matching index (What we want)
        elif len(matching_indexes) == 1:
            i = matching_indexes[0]
        #Checking to make sure there is only one macthing index
        elif len(matching_indexes) > 1:
            print(f"Index {index} has more than one matching index")
    
        # Calculate averages and assign to df1
        df1.at[index, 's_avg_05'] = df2.loc[i-5:i-1, 's'].mean()
        df1.at[index, 's_avg_1'] = df2.loc[i-10:i-6, 's'].mean()
        df1.at[index, 'bc_s_avg_05'] = df2.loc[i-5:i-1, 'bc_s'].mean()
        df1.at[index, 'bc_s_avg_1'] = df2.loc[i-10:i-6, 'bc_s'].mean()

    return df1

# Example usage:
# updated_df1 = compute_averages_modified(df1, df2)

In [411]:
tackles_1v1_1_master.drop(columns=['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1'], inplace=True)

In [436]:
tackles_1v1_1_master.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9735 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9735 non-null   int64  
 1   playId            9735 non-null   int64  
 2   nflId             9735 non-null   int64  
 3   tackle            9735 non-null   int64  
 4   assist            9735 non-null   int64  
 5   forcedFumble      9735 non-null   int64  
 6   pff_missedTackle  9735 non-null   int64  
 7   game_play_Id      9735 non-null   object 
 8   event_type        9735 non-null   float64
 9   s_avg_05          9734 non-null   object 
 10  s_avg_1           9734 non-null   object 
 11  bc_s_avg_05       9734 non-null   object 
 12  bc_s_avg_1        9734 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.3+ MB


Index 8689 has no matching index: DELETE gpId: 	2022103009_2259, nflId: 53592
Index 219 has no matching index: CORRECT gpId: 2022091805_2361, nflId: 52444
Index 455 has no matching index: CORRECT gpId:2022091102_189, nflId:52571
Index 696 has no matching index: CORRECT gpId: 2022091105_2742, nflId: 53450
Index 2449 has no matching index: CORRECT gpId: 2022092507_3091, nflId: 47899
Index 4667 has no matching index: CORRECT gpId: 2022100906_3322, nflId: 54574
Index 5135 has no matching index: CORRECT gpId: 2022101600_636, nflId: 54503
Index 6144 has no matching index: CORRECT gpId: 2022102300_2890, nflId: 52627
Index 7169 has no matching index: CORRECT gpId: 2022103009_2993, nflID: 43358
Index 7262 has no matching index: CORRECT gpId: 2022110600_2782,nflId:52594

In [416]:
tackles_1v1_1_speedtest = compute_speed_features_edited(tackles_1v1_1_master, tracking_clean_1)

Index 8689 has no matching index
Index 219 has no matching index
Index 455 has no matching index
Index 696 has no matching index
Index 2449 has no matching index
Index 4667 has no matching index
Index 5135 has no matching index
Index 6144 has no matching index
Index 7169 has no matching index
Index 7262 has no matching index


In [417]:
tackles_1v1_1_speedtest.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9735 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9735 non-null   int64  
 1   playId            9735 non-null   int64  
 2   nflId             9735 non-null   int64  
 3   tackle            9735 non-null   int64  
 4   assist            9735 non-null   int64  
 5   forcedFumble      9735 non-null   int64  
 6   pff_missedTackle  9735 non-null   int64  
 7   game_play_Id      9735 non-null   object 
 8   event_type        9735 non-null   float64
 9   s_avg_05          9734 non-null   object 
 10  s_avg_1           9734 non-null   object 
 11  bc_s_avg_05       9734 non-null   object 
 12  bc_s_avg_1        9734 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.3+ MB


**Dropping Strange Observation**

In [502]:
strange_obs = tackles_1v1_1_speedtest[tackles_1v1_1_speedtest[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

In [530]:
tackles_1v1_1_speedtest_nso = tackles_1v1_1_speedtest.drop(strange_obs.index)


In [531]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9734 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9734 non-null   int64  
 1   playId            9734 non-null   int64  
 2   nflId             9734 non-null   int64  
 3   tackle            9734 non-null   int64  
 4   assist            9734 non-null   int64  
 5   forcedFumble      9734 non-null   int64  
 6   pff_missedTackle  9734 non-null   int64  
 7   game_play_Id      9734 non-null   object 
 8   event_type        9734 non-null   float64
 9   s_avg_05          9734 non-null   object 
 10  s_avg_1           9734 non-null   object 
 11  bc_s_avg_05       9734 non-null   object 
 12  bc_s_avg_1        9734 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB


In [506]:
tackles_1v1_1_speedtest_nso[tackles_1v1_1_speedtest_nso[['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1']].isnull().all(axis=1)]

Empty DataFrame
Columns: [gameId, playId, nflId, tackle, assist, forcedFumble, pff_missedTackle, game_play_Id, event_type, s_avg_05, s_avg_1, bc_s_avg_05, bc_s_avg_1]
Index: []

**Dropping the out of bounds with missed tackle observations**


In [532]:
###Resetting Index of tackles_1v1_1_speedtest_nso so only tackle index and not missed tackle index gets dropped
tackles_1v1_1_speedtest_nso = tackles_1v1_1_speedtest_nso.reset_index(drop=True)

In [534]:
filtered_row_1 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091805_2361') & 
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 52444) & 
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_2 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091102_189') & 
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 52571) & 
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_3 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091105_2742') & 
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 53450) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_4 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022092507_3091') &  
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 47899) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_5 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022100906_3322') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 54574) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_6 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022101600_636') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 54503) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_7 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022102300_2890') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 52627) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_8 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022103009_2993') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 43358) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

filtered_row_9 = tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022110600_2782') &
                                            (tackles_1v1_1_speedtest_nso['nflId'] == 52594) &
                                            (tackles_1v1_1_speedtest_nso['event_type'] == 1)]

In [535]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9734 entries, 0 to 9733
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9734 non-null   int64  
 1   playId            9734 non-null   int64  
 2   nflId             9734 non-null   int64  
 3   tackle            9734 non-null   int64  
 4   assist            9734 non-null   int64  
 5   forcedFumble      9734 non-null   int64  
 6   pff_missedTackle  9734 non-null   int64  
 7   game_play_Id      9734 non-null   object 
 8   event_type        9734 non-null   float64
 9   s_avg_05          9734 non-null   object 
 10  s_avg_1           9734 non-null   object 
 11  bc_s_avg_05       9734 non-null   object 
 12  bc_s_avg_1        9734 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 988.7+ KB


In [536]:
for i in range(1, 10):
    # Get the DataFrame filtered_row_{i}
    filtered_rows = globals()[f'filtered_row_{i}']
    
    # Drop the rows from tackles_1v1_1_speedtest_nso
    tackles_1v1_1_speedtest_nso = tackles_1v1_1_speedtest_nso.drop(filtered_rows.index)

In [537]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9725 entries, 0 to 9733
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9725 non-null   int64  
 1   playId            9725 non-null   int64  
 2   nflId             9725 non-null   int64  
 3   tackle            9725 non-null   int64  
 4   assist            9725 non-null   int64  
 5   forcedFumble      9725 non-null   int64  
 6   pff_missedTackle  9725 non-null   int64  
 7   game_play_Id      9725 non-null   object 
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   object 
 10  s_avg_1           9725 non-null   object 
 11  bc_s_avg_05       9725 non-null   object 
 12  bc_s_avg_1        9725 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.0+ MB


In [538]:
tackles_1v1_1_speedtest_nso = tackles_1v1_1_speedtest_nso.reset_index(drop=True)

In [539]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9725 non-null   int64  
 1   playId            9725 non-null   int64  
 2   nflId             9725 non-null   int64  
 3   tackle            9725 non-null   int64  
 4   assist            9725 non-null   int64  
 5   forcedFumble      9725 non-null   int64  
 6   pff_missedTackle  9725 non-null   int64  
 7   game_play_Id      9725 non-null   object 
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   object 
 10  s_avg_1           9725 non-null   object 
 11  bc_s_avg_05       9725 non-null   object 
 12  bc_s_avg_1        9725 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 987.8+ KB


In [545]:
tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091110_750') & (tackles_1v1_1_speedtest_nso['nflId'] == 52546)]

gameId  playId  nflId  tackle  assist  forcedFumble  \
734   2022091110     750  52546       0       0             0   
9701  2022091110     750  52546       1       0             0   

      pff_missedTackle    game_play_Id  event_type s_avg_05 s_avg_1  \
734                  1  2022091110_750         2.0    1.456   2.868   
9701                 0  2022091110_750         1.0    1.456   2.868   

     bc_s_avg_05 bc_s_avg_1  
734        0.386        2.1  
9701       0.386        2.1

In [546]:
tackles_1v1_1_speedtest_nso[(tackles_1v1_1_speedtest_nso['game_play_Id'] == '2022091200_3723') & (tackles_1v1_1_speedtest_nso['nflId'] == 52435)]

gameId  playId  nflId  tackle  assist  forcedFumble  \
958   2022091200    3723  52435       0       0             0   
9702  2022091200    3723  52435       1       0             0   

      pff_missedTackle     game_play_Id  event_type s_avg_05 s_avg_1  \
958                  1  2022091200_3723         2.0     2.02   2.704   
9702                 0  2022091200_3723         1.0     2.02   2.704   

     bc_s_avg_05 bc_s_avg_1  
958        2.212      1.586  
9702       2.212      1.586

In [541]:
tackles_original = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/tackles.csv')

---

**Looking into observations regarding using 'first_contact' event for missed tackles**

In [577]:
double_tackles_original = tackles_original[(tackles_original['tackle'] == 1) & (tackles_original['pff_missedTackle'] == 1)]


In [579]:
double_tackles_original

gameId  playId  nflId  tackle  assist  forcedFumble  \
219   2022091805    2361  52444       1       0             0   
455   2022091102     189  52571       1       0             0   
696   2022091105    2742  53450       1       0             0   
935   2022091110     750  52546       1       0             0   
1213  2022091200    3723  52435       1       0             0   
1239  2022091801    3061  41270       1       0             0   
1445  2022091801    2090  41270       1       0             0   
2449  2022092507    3091  47899       1       0             0   
2610  2022091900     736  53451       1       0             0   
2817  2022091812    2620  47804       1       0             0   
2893  2022092503    4086  38548       1       0             0   
3055  2022100206    2702  47913       1       0             0   
3072  2022100209    2038  44926       1       0             0   
3865  2022100205    3163  47871       1       0             0   
3957  2022100902    1025  54543       1       0             0   
4289  2022100204     426  53592       1       0             0   
4647  2022100904    3777  52497       1       0             1   
4667  2022100906    3322  54574       1       0             0   
4862  2022101700    2126  46264       1       0             0   
4881  2022100911    2608  39984       1       0             0   
5135  2022101600     636  54503       1       0             0   
5144  2022101600    3211  46841       1       0             0   
6144  2022102300    2890  52627       1       0             0   
6390  2022102311    1564  38548       1       0             0   
7169  2022103009    2993  43358       1       0             0   
7262  2022110600    2782  52594       1       0             0   
8229  2022110601    3266  43503       1       0             0   
8241  2022110603     441  54653       1       0             0   
8555  2022102308     881  53509       1       0             0   
8683  2022103004     726  46669       1       0             0   
8936  2022100211    1393  54586       1       0             0   
9048  2022100906    2763  52435       1       0             0   
9170  2022101604     699  38559       1       0             0   
9575  2022110605    1030  53450       1       0             0   
9620  2022110610    2875  47971       1       0             0   

      pff_missedTackle  
219                  1  
455                  1  
696                  1  
935                  1  
1213                 1  
1239                 1  
1445                 1  
2449                 1  
2610                 1  
2817                 1  
2893                 1  
3055                 1  
3072                 1  
3865                 1  
3957                 1  
4289                 1  
4647                 1  
4667                 1  
4862                 1  
4881                 1  
5135                 1  
5144                 1  
6144                 1  
6390                 1  
7169                 1  
7262                 1  
8229                 1  
8241                 1  
8555                 1  
8683                 1  
8936                 1  
9048                 1  
9170                 1  
9575                 1  
9620                 1

In [580]:
#Function to create 'game_play_Id' column in DF
def game_play_Id(df):
    df['game_play_Id'] = df['gameId'].astype('str') + '_' + df['playId'].astype('str')

    return df

In [581]:
double_tackles_original = game_play_Id(double_tackles_original)

/var/folders/38/1m7d78r13mngspmlwjmj74480000gn/T/ipykernel_39743/2643504950.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['game_play_Id'] = df['gameId'].astype('str') + '_' + df['playId'].astype('str')


In [618]:
# Create an empty list to store the indices
indices = []

# Iterate over the rows in double_tackles_original
for index, row in double_tackles_original.iterrows():
    # Find the indices in tracking_clean_1 where 'game_play_Id' and 'nflId' are equal to the current row's values and 'event' is 'first_contact'
    matching_indices = tracking_clean_1[(tracking_clean_1['game_play_Id'] == row['game_play_Id']) & 
                                        (tracking_clean_1['nflId'] == row['nflId']) & 
                                        (tracking_clean_1['event'] == 'first_contact')].index
    
    if len(matching_indices) == 0:
        print(f"Index {index} has no matching index")
        continue
    elif len(matching_indices) == 1:
        i = matching_indices[0]
    elif len(matching_indices) > 1:
        print(f"Index {index} has more than one matching index")
        continue

    # Check if i - 10 has the same 'game_play_Id' and 'nflId' as i
    if (tracking_clean_1.loc[i - 10, 'game_play_Id'] != tracking_clean_1.loc[i, 'game_play_Id']) or (tracking_clean_1.loc[i - 10, 'nflId'] != tracking_clean_1.loc[i, 'nflId']):
            # If not, add i to the list of indices
            indices.append(i)

# Print the indices
print(indices)

Index 219 has no matching index
Index 8936 has no matching index
[285344, 553684, 778691, 785306, 816954]


In [617]:
double_tackles_original

gameId  playId  nflId  tackle  assist  forcedFumble  \
219   2022091805    2361  52444       1       0             0   
455   2022091102     189  52571       1       0             0   
696   2022091105    2742  53450       1       0             0   
935   2022091110     750  52546       1       0             0   
1213  2022091200    3723  52435       1       0             0   
1239  2022091801    3061  41270       1       0             0   
1445  2022091801    2090  41270       1       0             0   
2449  2022092507    3091  47899       1       0             0   
2610  2022091900     736  53451       1       0             0   
2817  2022091812    2620  47804       1       0             0   
2893  2022092503    4086  38548       1       0             0   
3055  2022100206    2702  47913       1       0             0   
3072  2022100209    2038  44926       1       0             0   
3865  2022100205    3163  47871       1       0             0   
3957  2022100902    1025  54543       1       0             0   
4289  2022100204     426  53592       1       0             0   
4647  2022100904    3777  52497       1       0             1   
4667  2022100906    3322  54574       1       0             0   
4862  2022101700    2126  46264       1       0             0   
4881  2022100911    2608  39984       1       0             0   
5135  2022101600     636  54503       1       0             0   
5144  2022101600    3211  46841       1       0             0   
6144  2022102300    2890  52627       1       0             0   
6390  2022102311    1564  38548       1       0             0   
7169  2022103009    2993  43358       1       0             0   
7262  2022110600    2782  52594       1       0             0   
8229  2022110601    3266  43503       1       0             0   
8241  2022110603     441  54653       1       0             0   
8555  2022102308     881  53509       1       0             0   
8683  2022103004     726  46669       1       0             0   
8936  2022100211    1393  54586       1       0             0   
9048  2022100906    2763  52435       1       0             0   
9170  2022101604     699  38559       1       0             0   
9575  2022110605    1030  53450       1       0             0   
9620  2022110610    2875  47971       1       0             0   

      pff_missedTackle     game_play_Id  
219                  1  2022091805_2361  
455                  1   2022091102_189  
696                  1  2022091105_2742  
935                  1   2022091110_750  
1213                 1  2022091200_3723  
1239                 1  2022091801_3061  
1445                 1  2022091801_2090  
2449                 1  2022092507_3091  
2610                 1   2022091900_736  
2817                 1  2022091812_2620  
2893                 1  2022092503_4086  
3055                 1  2022100206_2702  
3072                 1  2022100209_2038  
3865                 1  2022100205_3163  
3957                 1  2022100902_1025  
4289                 1   2022100204_426  
4647                 1  2022100904_3777  
4667                 1  2022100906_3322  
4862                 1  2022101700_2126  
4881                 1  2022100911_2608  
5135                 1   2022101600_636  
5144                 1  2022101600_3211  
6144                 1  2022102300_2890  
6390                 1  2022102311_1564  
7169                 1  2022103009_2993  
7262                 1  2022110600_2782  
8229                 1  2022110601_3266  
8241                 1   2022110603_441  
8555                 1   2022102308_881  
8683                 1   2022103004_726  
8936                 1  2022100211_1393  
9048                 1  2022100906_2763  
9170                 1   2022101604_699  
9575                 1  2022110605_1030  
9620                 1  2022110610_2875

**Changing observation at Index 164 back (219 in original) back to event_type 2.0 due to lack of first_contact event**

In [657]:
tackles_1v1_1_all_features.event_type.value_counts()

event_type
1.0    7775
2.0    1858
3.0      59
4.0      33
Name: count, dtype: int64

In [658]:
tackles_1v1_1_all_features.at[164, 'event_type'] = 2.0

In [660]:
tackles_1v1_1_all_features.event_type.value_counts()

event_type
1.0    7775
2.0    1859
3.0      59
4.0      32
Name: count, dtype: int64

In [661]:
tackles_1v1_1_all_features[tackles_1v1_1_all_features['event_type']== 4]

gameId  playId  nflId  tackle  assist  forcedFumble  \
357   2022091102     189  52571       0       0             0   
542   2022091105    2742  53450       0       0             0   
734   2022091110     750  52546       0       0             0   
958   2022091200    3723  52435       0       0             0   
981   2022091801    3061  41270       0       0             0   
1129  2022091801    2090  41270       0       0             0   
1937  2022092507    3091  47899       0       0             0   
2066  2022091900     736  53451       0       0             0   
2232  2022091812    2620  47804       0       0             0   
2294  2022092503    4086  38548       0       0             0   
2422  2022100206    2702  47913       0       0             0   
2438  2022100209    2038  44926       0       0             0   
3068  2022100205    3163  47871       0       0             0   
3145  2022100902    1025  54543       0       0             0   
3413  2022100204     426  53592       0       0             0   
3701  2022100906    3322  54574       0       0             0   
3862  2022101700    2126  46264       0       0             0   
3879  2022100911    2608  39984       0       0             0   
4082  2022101600     636  54503       0       0             0   
4089  2022101600    3211  46841       0       0             0   
4876  2022102300    2890  52627       0       0             0   
5078  2022102311    1564  38548       0       0             0   
5677  2022103009    2993  43358       0       0             0   
5749  2022110600    2782  52594       0       0             0   
6518  2022110601    3266  43503       0       0             0   
6527  2022110603     441  54653       0       0             0   
6783  2022102308     881  53509       0       0             0   
6882  2022103004     726  46669       0       0             0   
7168  2022100906    2763  52435       0       0             0   
7266  2022101604     699  38559       0       0             0   
7584  2022110605    1030  53450       0       0             0   
7623  2022110610    2875  47971       0       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
357                  1   2022091102_189         4.0     6.090    6.108   
542                  1  2022091105_2742         4.0     8.682    8.116   
734                  1   2022091110_750         4.0     2.614    4.244   
958                  1  2022091200_3723         4.0     2.492    2.772   
981                  1  2022091801_3061         4.0     2.622    2.930   
1129                 1  2022091801_2090         4.0     4.390    5.196   
1937                 1  2022092507_3091         4.0     4.286    5.076   
2066                 1   2022091900_736         4.0     2.986    2.266   
2232                 1  2022091812_2620         4.0     2.482    5.536   
2294                 1  2022092503_4086         4.0     7.696    7.508   
2422                 1  2022100206_2702         4.0     5.540    6.210   
2438                 1  2022100209_2038         4.0     5.938    6.312   
3068                 1  2022100205_3163         4.0     5.042    4.342   
3145                 1  2022100902_1025         4.0     2.456    2.350   
3413                 1   2022100204_426         4.0     2.958    3.436   
3701                 1  2022100906_3322         4.0     9.672    9.726   
3862                 1  2022101700_2126         4.0     1.284    1.492   
3879                 1  2022100911_2608         4.0     3.884    2.932   
4082                 1   2022101600_636         4.0     4.864    3.126   
4089                 1  2022101600_3211         4.0     4.848    5.444   
4876                 1  2022102300_2890         4.0     4.412    3.960   
5078                 1  2022102311_1564         4.0     5.942    5.708   
5677                 1  2022103009_2993         4.0     7.554    7.272   
5749                 1  2022110600_2782         4.0     7.884    6.952   
6518          

**Finding observations that match indices without a full second of data before them from tracking_clean_1**

In [662]:
# Get the 'game_play_Id' and 'nflId' values from tracking_clean_1 at the specified indices
game_play_ids = tracking_clean_1.loc[[285344, 553684, 778691, 785306, 816954], 'game_play_Id']
nfl_ids = tracking_clean_1.loc[[285344, 553684, 778691, 785306, 816954], 'nflId']

# Find the rows in tackles_1v1_1_newest where 'game_play_Id' and 'nflId' are in the lists
matching_rows = tackles_1v1_1_all_features[(tackles_1v1_1_all_features['game_play_Id'].isin(game_play_ids)) & 
                                     (tackles_1v1_1_all_features['nflId'].isin(nfl_ids))]

# Get the indices of the matching rows
matching_indices = matching_rows.index

# Print the indices
print(matching_indices)

Index([2066, 2438, 4082, 4089, 7266, 9705, 9709, 9715, 9722], dtype='int64')


In [663]:
tackles_1v1_1_all_features.iloc[matching_indices]

gameId  playId  nflId  tackle  assist  forcedFumble  \
2066  2022091900     736  53451       0       0             0   
2438  2022100209    2038  44926       0       0             0   
4082  2022101600     636  54503       0       0             0   
4089  2022101600    3211  46841       0       0             0   
7266  2022101604     699  38559       0       0             0   
9705  2022091900     736  53451       1       0             0   
9709  2022100209    2038  44926       1       0             0   
9715  2022101600    3211  46841       1       0             0   
9722  2022101604     699  38559       1       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
2066                 1   2022091900_736         4.0     2.986    2.266   
2438                 1  2022100209_2038         4.0     5.938    6.312   
4082                 1   2022101600_636         4.0     4.864    3.126   
4089                 1  2022101600_3211         4.0     4.848    5.444   
7266                 1   2022101604_699         4.0     4.402    3.902   
9705                 0   2022091900_736         1.0     2.654    0.846   
9709                 0  2022100209_2038         1.0     2.170    3.888   
9715                 0  2022101600_3211         1.0     3.430    3.336   
9722                 0   2022101604_699         1.0     0.846    1.470   

      bc_s_avg_05  bc_s_avg_1 cos_avg_05 cos_avg_1 do_avg_05  do_avg_1  \
2066        1.498       0.874   0.922129  0.886142  0.845711    0.9148   
2438        5.166       5.480   0.852892  0.412437  0.706911  0.459156   
4082        5.450       4.134   0.863155  0.956389     0.814  0.696311   
4089        3.366       1.972   -0.57449 -0.495644  0.822822  0.840978   
7266        3.812       4.904   0.717871  0.776895  0.700533  0.320911   
9705        0.986       1.014   0.946746  0.687905  0.950711  0.435178   
9709        1.316       3.746   0.851791  0.989272  0.354111    0.8498   
9715        4.948       5.330   0.864697  0.573301  0.901689  0.647911   
9722        4.854       3.626  -0.870827 -0.519733  0.156311     0.794   

     bc_do_avg_05 bc_do_avg_1  
2066     0.830444    0.877333  
2438     0.582689    0.376756  
4082     0.626533    0.437067  
4089       0.6288    0.601133  
7266     0.812444    0.708956  
9705     0.881356    0.347311  
9709     0.345333    0.622511  
9715     0.256711    0.670222  
9722       0.5676    0.438711

In [664]:
tracking_clean_1.iloc[indices]

gameId  playId    nflId       displayName  frameId  \
285344  2022091900     736  53451.0      Caleb Farley        7   
553684  2022100209    2038  44926.0  Rayshawn Jenkins        7   
778691  2022101600     636  54503.0   Arnold Ebiketie        7   
785306  2022101600    3211  46841.0    Matt Dickerson        8   
816954  2022101604     699  38559.0    Harrison Smith       10   

                              time  jerseyNumber club playDirection      x  \
285344  2022-09-19 19:48:09.799999           3.0  TEN          left  68.79   
553684  2022-10-02 14:40:20.500000           2.0  JAX         right  51.86   
778691  2022-10-16 13:29:16.500000          47.0  ATL         right  24.95   
785306  2022-10-16 15:35:47.500000          91.0  ATL         right  56.96   
816954  2022-10-16 13:27:08.400000          22.0  MIN         right  80.84   

            y     s     a   dis       o     dir          event  \
285344   6.05  4.78  2.79  0.46   80.36  127.99  first_contact   
553684  25.80  5.97  4.55  0.59  165.18  119.29  first_contact   
778691  10.66  4.88  2.47  0.50  191.84  151.66  first_contact   
785306  21.39  3.95  3.23  0.41  157.86  172.42  first_contact   
816954  32.40  4.44  0.81  0.45  229.53  223.88  first_contact   

           game_play_Id defensiveTeam  ballCarrierId    bcx    bcy  bc_s  \
285344   2022091900_736           TEN          42489  69.23   6.52  0.61   
553684  2022100209_2038           JAX          47834  53.38  21.74  5.77   
778691   2022101600_636           ATL          47819  25.12   9.09  1.14   
785306  2022101600_3211           ATL          47819  60.05  12.64  1.14   
816954   2022101604_699           MIN          53435  80.52  32.22  3.23   

        bc_a  bc_dis    bc_o  bc_dir  distance_from_bc  tackler_one  \
285344  3.55    0.05   33.87   60.41          0.643817      53451.0   
553684  2.31    0.59   66.03   43.17          4.335205      44926.0   
778691  1.52    0.11   42.63  265.12          1.579177      54503.0   
785306  4.66    0.13  102.01  318.22          9.279580      46841.0   
816954  2.89    0.33  181.92  182.96          0.367151      38559.0   

        tackler_two  assister_one  assister_two  missed_tackler_1  \
285344          NaN           NaN           NaN           53451.0   
553684          NaN           NaN           NaN           44926.0   
778691          NaN           NaN           NaN           54503.0   
785306          NaN           NaN           NaN           46841.0   
816954          NaN           NaN           NaN           38559.0   

        missed_tackler_2  missed_tackler_3  missed_tackler_4  \
285344               NaN               NaN               NaN   
553684               NaN               NaN               NaN   
778691           52424.0               NaN               NaN   
785306           46135.0           38592.0               NaN   
816954               NaN               NaN               NaN   

        missed_tackler_5  missed_tackler_6 new_event    cosine  do_align  \
285344               NaN               NaN       NaN  0.381393  0.470778   
553684               NaN               NaN       NaN  0.239889  0.490111   
778691               NaN               NaN       NaN -0.398109  0.553556   
785306               NaN               NaN       NaN -0.827081  0.838222   
816954               NaN               NaN       NaN  0.755625  0.937222   

        bc_do_align  weight  bc_weight    force  bc_force  
285344     0.705111     207        191   577.53    678.05  
553684     0.746000     220        226  1001.00    522.06  
778691    -0.527889     256        214   632.32    325.28  
785306    -0.597667     290        214   936.70    997.24  
816954     0.988444     214        182   173.34    525.98

In [665]:
matching_indices_drop = matching_indices[0:5]

In [666]:
tackles_1v1_1_all_features.iloc[matching_indices_drop]

gameId  playId  nflId  tackle  assist  forcedFumble  \
2066  2022091900     736  53451       0       0             0   
2438  2022100209    2038  44926       0       0             0   
4082  2022101600     636  54503       0       0             0   
4089  2022101600    3211  46841       0       0             0   
7266  2022101604     699  38559       0       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
2066                 1   2022091900_736         4.0     2.986    2.266   
2438                 1  2022100209_2038         4.0     5.938    6.312   
4082                 1   2022101600_636         4.0     4.864    3.126   
4089                 1  2022101600_3211         4.0     4.848    5.444   
7266                 1   2022101604_699         4.0     4.402    3.902   

      bc_s_avg_05  bc_s_avg_1 cos_avg_05 cos_avg_1 do_avg_05  do_avg_1  \
2066        1.498       0.874   0.922129  0.886142  0.845711    0.9148   
2438        5.166       5.480   0.852892  0.412437  0.706911  0.459156   
4082        5.450       4.134   0.863155  0.956389     0.814  0.696311   
4089        3.366       1.972   -0.57449 -0.495644  0.822822  0.840978   
7266        3.812       4.904   0.717871  0.776895  0.700533  0.320911   

     bc_do_avg_05 bc_do_avg_1  
2066     0.830444    0.877333  
2438     0.582689    0.376756  
4082     0.626533    0.437067  
4089       0.6288    0.601133  
7266     0.812444    0.708956

In [669]:
tackles_1v1_1_all_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9725 non-null   int64  
 1   playId            9725 non-null   int64  
 2   nflId             9725 non-null   int64  
 3   tackle            9725 non-null   int64  
 4   assist            9725 non-null   int64  
 5   forcedFumble      9725 non-null   int64  
 6   pff_missedTackle  9725 non-null   int64  
 7   game_play_Id      9725 non-null   object 
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   float64
 10  s_avg_1           9725 non-null   float64
 11  bc_s_avg_05       9725 non-null   float64
 12  bc_s_avg_1        9725 non-null   float64
 13  cos_avg_05        9717 non-null   object 
 14  cos_avg_1         9721 non-null   object 
 15  do_avg_05         9725 non-null   object 
 16  do_avg_1          9725 non-null   object 


In [670]:
###Dropping the 5 observations where there is no data at least 1 second before 'first_contact' event
tackles_1v1_1_af_drop5 = tackles_1v1_1_all_features.drop(matching_indices_drop)

In [671]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9712 non-null   object 
 14  cos_avg_1         9716 non-null   object 
 15  do_avg_05         9720 non-null   object 
 16  do_avg_1          9720 non-null   object 
 17  

In [672]:
tackles_1v1_1_af_drop5[(tackles_1v1_1_af_drop5['game_play_Id'] == '2022100211_1393') & (tackles_1v1_1_af_drop5['nflId'] == 54586)]

Empty DataFrame
Columns: [gameId, playId, nflId, tackle, assist, forcedFumble, pff_missedTackle, game_play_Id, event_type, s_avg_05, s_avg_1, bc_s_avg_05, bc_s_avg_1, cos_avg_05, cos_avg_1, do_avg_05, do_avg_1, bc_do_avg_05, bc_do_avg_1]
Index: []

In [582]:
double_tackles_original.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 219 to 9620
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   gameId            35 non-null     int64 
 1   playId            35 non-null     int64 
 2   nflId             35 non-null     int64 
 3   tackle            35 non-null     int64 
 4   assist            35 non-null     int64 
 5   forcedFumble      35 non-null     int64 
 6   pff_missedTackle  35 non-null     int64 
 7   game_play_Id      35 non-null     object
dtypes: int64(7), object(1)
memory usage: 2.5+ KB


---

**Re-running speed features**

In [547]:
tackles_1v1_1_speedtest_nso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9725 non-null   int64  
 1   playId            9725 non-null   int64  
 2   nflId             9725 non-null   int64  
 3   tackle            9725 non-null   int64  
 4   assist            9725 non-null   int64  
 5   forcedFumble      9725 non-null   int64  
 6   pff_missedTackle  9725 non-null   int64  
 7   game_play_Id      9725 non-null   object 
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   object 
 10  s_avg_1           9725 non-null   object 
 11  bc_s_avg_05       9725 non-null   object 
 12  bc_s_avg_1        9725 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 987.8+ KB


In [548]:
tackles_1v1_1_updated = tackles_1v1_1_speedtest_nso.drop(columns=['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1'])

In [549]:
tackles_1v1_1_updated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9725 non-null   int64  
 1   playId            9725 non-null   int64  
 2   nflId             9725 non-null   int64  
 3   tackle            9725 non-null   int64  
 4   assist            9725 non-null   int64  
 5   forcedFumble      9725 non-null   int64  
 6   pff_missedTackle  9725 non-null   int64  
 7   game_play_Id      9725 non-null   object 
 8   event_type        9725 non-null   float64
dtypes: float64(1), int64(7), object(1)
memory usage: 683.9+ KB


In [552]:
###Re-running speed computation to see if the events with both a missed tackle an dtackle originally get properly calculated
tackles_1v1_1_newest = compute_speed_features_edited(tackles_1v1_1_updated, tracking_clean_1)

In [553]:
tackles_1v1_1_newest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9725 non-null   int64  
 1   playId            9725 non-null   int64  
 2   nflId             9725 non-null   int64  
 3   tackle            9725 non-null   int64  
 4   assist            9725 non-null   int64  
 5   forcedFumble      9725 non-null   int64  
 6   pff_missedTackle  9725 non-null   int64  
 7   game_play_Id      9725 non-null   object 
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   object 
 10  s_avg_1           9725 non-null   object 
 11  bc_s_avg_05       9725 non-null   object 
 12  bc_s_avg_1        9725 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 987.8+ KB


In [555]:
tackles_1v1_1_newest.head()

gameId  playId  nflId  tackle  assist  forcedFumble  pff_missedTackle  \
0  2022090800     101  42816       1       0             0                 0   
1  2022090800     393  46232       1       0             0                 0   
2  2022090800     486  40166       1       0             0                 0   
3  2022090800     646  47939       1       0             0                 0   
4  2022090800     818  40107       1       0             0                 0   

     game_play_Id  event_type s_avg_05 s_avg_1 bc_s_avg_05 bc_s_avg_1  
0  2022090800_101         1.0     3.52   4.332       5.694       6.83  
1  2022090800_393         1.0    2.164   1.706       0.298      0.336  
2  2022090800_486         1.0    2.332   2.274         3.0      2.376  
3  2022090800_646         1.0    4.274   5.334       4.364       5.72  
4  2022090800_818         1.0    0.854   1.828       1.448      2.134

In [556]:
tackles_1v1_1_newest['s_avg_05'] = tackles_1v1_1_newest['s_avg_05'].astype(float)
tackles_1v1_1_newest['s_avg_1'] = tackles_1v1_1_newest['s_avg_1'].astype(float)
tackles_1v1_1_newest['bc_s_avg_05'] = tackles_1v1_1_newest['bc_s_avg_05'].astype(float)
tackles_1v1_1_newest['bc_s_avg_1'] = tackles_1v1_1_newest['bc_s_avg_1'].astype(float)

In [557]:
tackles_1v1_1_newest.head()

gameId  playId  nflId  tackle  assist  forcedFumble  pff_missedTackle  \
0  2022090800     101  42816       1       0             0                 0   
1  2022090800     393  46232       1       0             0                 0   
2  2022090800     486  40166       1       0             0                 0   
3  2022090800     646  47939       1       0             0                 0   
4  2022090800     818  40107       1       0             0                 0   

     game_play_Id  event_type  s_avg_05  s_avg_1  bc_s_avg_05  bc_s_avg_1  
0  2022090800_101         1.0     3.520    4.332        5.694       6.830  
1  2022090800_393         1.0     2.164    1.706        0.298       0.336  
2  2022090800_486         1.0     2.332    2.274        3.000       2.376  
3  2022090800_646         1.0     4.274    5.334        4.364       5.720  
4  2022090800_818         1.0     0.854    1.828        1.448       2.134

In [558]:
tackles_1v1_1_newest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9725 non-null   int64  
 1   playId            9725 non-null   int64  
 2   nflId             9725 non-null   int64  
 3   tackle            9725 non-null   int64  
 4   assist            9725 non-null   int64  
 5   forcedFumble      9725 non-null   int64  
 6   pff_missedTackle  9725 non-null   int64  
 7   game_play_Id      9725 non-null   object 
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   float64
 10  s_avg_1           9725 non-null   float64
 11  bc_s_avg_05       9725 non-null   float64
 12  bc_s_avg_1        9725 non-null   float64
dtypes: float64(5), int64(7), object(1)
memory usage: 987.8+ KB


In [559]:
tackles_1v1_1_newest[(tackles_1v1_1_newest['game_play_Id'] == '2022091110_750') & (tackles_1v1_1_newest['nflId'] == 52546)]

gameId  playId  nflId  tackle  assist  forcedFumble  \
734   2022091110     750  52546       0       0             0   
9701  2022091110     750  52546       1       0             0   

      pff_missedTackle    game_play_Id  event_type  s_avg_05  s_avg_1  \
734                  1  2022091110_750         2.0     2.614    4.244   
9701                 0  2022091110_750         1.0     1.456    2.868   

      bc_s_avg_05  bc_s_avg_1  
734         1.754       3.382  
9701        0.386       2.100

In [560]:
tackles_1v1_1_newest[(tackles_1v1_1_newest['game_play_Id'] == '2022091200_3723') & (tackles_1v1_1_newest['nflId'] == 52435)]

gameId  playId  nflId  tackle  assist  forcedFumble  \
958   2022091200    3723  52435       0       0             0   
9702  2022091200    3723  52435       1       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
958                  1  2022091200_3723         2.0     2.492    2.772   
9702                 0  2022091200_3723         1.0     2.020    2.704   

      bc_s_avg_05  bc_s_avg_1  
958         1.804       1.294  
9702        2.212       1.586

In [568]:
tracking_clean_1[(tracking_clean_1['game_play_Id'] == '2022091801_2090') & (tracking_clean_1['nflId'] == 41270)]

gameId  playId    nflId      displayName  frameId  \
175881  2022091801    2090  41270.0  Lamarcus Joyner        1   
175882  2022091801    2090  41270.0  Lamarcus Joyner        2   
175883  2022091801    2090  41270.0  Lamarcus Joyner        3   
175884  2022091801    2090  41270.0  Lamarcus Joyner        4   
175885  2022091801    2090  41270.0  Lamarcus Joyner        5   
175886  2022091801    2090  41270.0  Lamarcus Joyner        6   
175887  2022091801    2090  41270.0  Lamarcus Joyner        7   
175888  2022091801    2090  41270.0  Lamarcus Joyner        8   
175889  2022091801    2090  41270.0  Lamarcus Joyner        9   
175890  2022091801    2090  41270.0  Lamarcus Joyner       10   
175891  2022091801    2090  41270.0  Lamarcus Joyner       11   
175892  2022091801    2090  41270.0  Lamarcus Joyner       12   
175893  2022091801    2090  41270.0  Lamarcus Joyner       13   
175894  2022091801    2090  41270.0  Lamarcus Joyner       14   
175895  2022091801    2090  41270.0  Lamarcus Joyner       15   
175896  2022091801    2090  41270.0  Lamarcus Joyner       16   
175897  2022091801    2090  41270.0  Lamarcus Joyner       17   
175898  2022091801    2090  41270.0  Lamarcus Joyner       18   
175899  2022091801    2090  41270.0  Lamarcus Joyner       19   
175900  2022091801    2090  41270.0  Lamarcus Joyner       20   
175901  2022091801    2090  41270.0  Lamarcus Joyner       21   
175902  2022091801    2090  41270.0  Lamarcus Joyner       22   
175903  2022091801    2090  41270.0  Lamarcus Joyner       23   
175904  2022091801    2090  41270.0  Lamarcus Joyner       24   
175905  2022091801    2090  41270.0  Lamarcus Joyner       25   
175906  2022091801    2090  41270.0  Lamarcus Joyner       26   
175907  2022091801    2090  41270.0  Lamarcus Joyner       27   
175908  2022091801    2090  41270.0  Lamarcus Joyner       28   
175909  2022091801    2090  41270.0  Lamarcus Joyner       29   
175910  2022091801    2090  41270.0  Lamarcus Joyner       30   
175911  2022091801    2090  41270.0  Lamarcus Joyner       31   
175912  2022091801    2090  41270.0  Lamarcus Joyner       32   
175913  2022091801    2090  41270.0  Lamarcus Joyner       33   
175914  2022091801    2090  41270.0  Lamarcus Joyner       34   
175915  2022091801    2090  41270.0  Lamarcus Joyner       35   
175916  2022091801    2090  41270.0  Lamarcus Joyner       36   
175917  2022091801    2090  41270.0  Lamarcus Joyner       37   
175918  2022091801    2090  41270.0  Lamarcus Joyner       38   
175919  2022091801    2090  41270.0  Lamarcus Joyner       39   
175920  2022091801    2090  41270.0  Lamarcus Joyner       40   
175921  2022091801    2090  41270.0  Lamarcus Joyner       41   
175922  2022091801    2090  41270.0  Lamarcus Joyner       42   
175923  2022091801    2090  41270.0  Lamarcus Joyner       43   
175924  2022091801    2090  41270.0  Lamarcus Joyner       44   
175925  2022091801    2090  41270.0  Lamarcus Joyner       45   
175926  2022091801    2090  41270.0  Lamarcus Joyner       46   
175927  2022091801    2090  41270.0  Lamarcus Joyner       47   
175928  2022091801    2090  41270.0  Lamarcus Joyner       48   
175929  2022091801    2090  41270.0  Lamarcus Joyner       49   
175930  2022091801    2090  41270.0  Lamarcus Joyner       50   
175931  2022091801    2090  41270.0  Lamarcus Joyner       51   
175932  2022091801    2090  41270.0  Lamarcus Joyner       52   
175933  2022091801    2090  41270.0  Lamarcus Joyner       53   
175934  2022091801    2090  41270.0  Lamarcus Joyner       54   
175935  2022091801    2090  41270.0  Lamarcus Joyner       55   
175936  2022091801    2090  41270.0  Lamarcus Joyner       56   
175937  2022091801    2090  41270.0  Lamarcus Joyner       57   
175938  2022091801    2090  41270.0  Lamarcus Joyner       58   

                              time  jerseyNumber club playDirection      x  \
175881  2022-09-18 14:39:11.900000          29.0  NYJ         right  65.10   
175882  2022-09-18 1

In [567]:
long_play_2[:60]

gameId  playId    nflId      displayName  frameId  \
178471  2022091801    3061  41270.0  Lamarcus Joyner        1   
178472  2022091801    3061  41270.0  Lamarcus Joyner        2   
178473  2022091801    3061  41270.0  Lamarcus Joyner        3   
178474  2022091801    3061  41270.0  Lamarcus Joyner        4   
178475  2022091801    3061  41270.0  Lamarcus Joyner        5   
178476  2022091801    3061  41270.0  Lamarcus Joyner        6   
178477  2022091801    3061  41270.0  Lamarcus Joyner        7   
178478  2022091801    3061  41270.0  Lamarcus Joyner        8   
178479  2022091801    3061  41270.0  Lamarcus Joyner        9   
178480  2022091801    3061  41270.0  Lamarcus Joyner       10   
178481  2022091801    3061  41270.0  Lamarcus Joyner       11   
178482  2022091801    3061  41270.0  Lamarcus Joyner       12   
178483  2022091801    3061  41270.0  Lamarcus Joyner       13   
178484  2022091801    3061  41270.0  Lamarcus Joyner       14   
178485  2022091801    3061  41270.0  Lamarcus Joyner       15   
178486  2022091801    3061  41270.0  Lamarcus Joyner       16   
178487  2022091801    3061  41270.0  Lamarcus Joyner       17   
178488  2022091801    3061  41270.0  Lamarcus Joyner       18   
178489  2022091801    3061  41270.0  Lamarcus Joyner       19   
178490  2022091801    3061  41270.0  Lamarcus Joyner       20   
178491  2022091801    3061  41270.0  Lamarcus Joyner       21   
178492  2022091801    3061  41270.0  Lamarcus Joyner       22   
178493  2022091801    3061  41270.0  Lamarcus Joyner       23   
178494  2022091801    3061  41270.0  Lamarcus Joyner       24   
178495  2022091801    3061  41270.0  Lamarcus Joyner       25   
178496  2022091801    3061  41270.0  Lamarcus Joyner       26   
178497  2022091801    3061  41270.0  Lamarcus Joyner       27   
178498  2022091801    3061  41270.0  Lamarcus Joyner       28   
178499  2022091801    3061  41270.0  Lamarcus Joyner       29   
178500  2022091801    3061  41270.0  Lamarcus Joyner       30   
178501  2022091801    3061  41270.0  Lamarcus Joyner       31   
178502  2022091801    3061  41270.0  Lamarcus Joyner       32   
178503  2022091801    3061  41270.0  Lamarcus Joyner       33   
178504  2022091801    3061  41270.0  Lamarcus Joyner       34   
178505  2022091801    3061  41270.0  Lamarcus Joyner       35   
178506  2022091801    3061  41270.0  Lamarcus Joyner       36   
178507  2022091801    3061  41270.0  Lamarcus Joyner       37   
178508  2022091801    3061  41270.0  Lamarcus Joyner       38   
178509  2022091801    3061  41270.0  Lamarcus Joyner       39   
178510  2022091801    3061  41270.0  Lamarcus Joyner       40   
178511  2022091801    3061  41270.0  Lamarcus Joyner       41   
178512  2022091801    3061  41270.0  Lamarcus Joyner       42   
178513  2022091801    3061  41270.0  Lamarcus Joyner       43   
178514  2022091801    3061  41270.0  Lamarcus Joyner       44   
178515  2022091801    3061  41270.0  Lamarcus Joyner       45   
178516  2022091801    3061  41270.0  Lamarcus Joyner       46   
178517  2022091801    3061  41270.0  Lamarcus Joyner       47   
178518  2022091801    3061  41270.0  Lamarcus Joyner       48   
178519  2022091801    3061  41270.0  Lamarcus Joyner       49   
178520  2022091801    3061  41270.0  Lamarcus Joyner       50   
178521  2022091801    3061  41270.0  Lamarcus Joyner       51   
178522  2022091801    3061  41270.0  Lamarcus Joyner       52   
178523  2022091801    3061  41270.0  Lamarcus Joyner       53   
178524  2022091801    3061  41270.0  Lamarcus Joyner       54   
178525  2022091801    3061  41270.0  Lamarcus Joyner       55   
178526  2022091801    3061  41270.0  Lamarcus Joyner       56   
178527  2022091801    3061  41270.0  Lamarcus Joyner       57   
178528  2022091801    3061  41270.0  Lamarcus Joyner       58   
178529  2022091801    3061  41270.0  Lamarcus Joyner       59   
178530  2022091801    3061  41270.0  Lamarcus Joyner       60   

                              time  jerseyNumb

In [562]:
long_play = tracking_clean_1[(tracking_clean_1['game_play_Id'] == '2022091200_3723') & (tracking_clean_1['nflId'] == 52435)]

In [563]:
long_play[0:60]

gameId  playId    nflId    displayName  frameId  \
151595  2022091200    3723  52435.0  Jordyn Brooks        1   
151596  2022091200    3723  52435.0  Jordyn Brooks        2   
151597  2022091200    3723  52435.0  Jordyn Brooks        3   
151598  2022091200    3723  52435.0  Jordyn Brooks        4   
151599  2022091200    3723  52435.0  Jordyn Brooks        5   
151600  2022091200    3723  52435.0  Jordyn Brooks        6   
151601  2022091200    3723  52435.0  Jordyn Brooks        7   
151602  2022091200    3723  52435.0  Jordyn Brooks        8   
151603  2022091200    3723  52435.0  Jordyn Brooks        9   
151604  2022091200    3723  52435.0  Jordyn Brooks       10   
151605  2022091200    3723  52435.0  Jordyn Brooks       11   
151606  2022091200    3723  52435.0  Jordyn Brooks       12   
151607  2022091200    3723  52435.0  Jordyn Brooks       13   
151608  2022091200    3723  52435.0  Jordyn Brooks       14   
151609  2022091200    3723  52435.0  Jordyn Brooks       15   
151610  2022091200    3723  52435.0  Jordyn Brooks       16   
151611  2022091200    3723  52435.0  Jordyn Brooks       17   
151612  2022091200    3723  52435.0  Jordyn Brooks       18   
151613  2022091200    3723  52435.0  Jordyn Brooks       19   
151614  2022091200    3723  52435.0  Jordyn Brooks       20   
151615  2022091200    3723  52435.0  Jordyn Brooks       21   
151616  2022091200    3723  52435.0  Jordyn Brooks       22   
151617  2022091200    3723  52435.0  Jordyn Brooks       23   
151618  2022091200    3723  52435.0  Jordyn Brooks       24   
151619  2022091200    3723  52435.0  Jordyn Brooks       25   
151620  2022091200    3723  52435.0  Jordyn Brooks       26   
151621  2022091200    3723  52435.0  Jordyn Brooks       27   
151622  2022091200    3723  52435.0  Jordyn Brooks       28   
151623  2022091200    3723  52435.0  Jordyn Brooks       29   
151624  2022091200    3723  52435.0  Jordyn Brooks       30   
151625  2022091200    3723  52435.0  Jordyn Brooks       31   
151626  2022091200    3723  52435.0  Jordyn Brooks       32   
151627  2022091200    3723  52435.0  Jordyn Brooks       33   
151628  2022091200    3723  52435.0  Jordyn Brooks       34   
151629  2022091200    3723  52435.0  Jordyn Brooks       35   
151630  2022091200    3723  52435.0  Jordyn Brooks       36   
151631  2022091200    3723  52435.0  Jordyn Brooks       37   
151632  2022091200    3723  52435.0  Jordyn Brooks       38   
151633  2022091200    3723  52435.0  Jordyn Brooks       39   
151634  2022091200    3723  52435.0  Jordyn Brooks       40   
151635  2022091200    3723  52435.0  Jordyn Brooks       41   
151636  2022091200    3723  52435.0  Jordyn Brooks       42   
151637  2022091200    3723  52435.0  Jordyn Brooks       43   
151638  2022091200    3723  52435.0  Jordyn Brooks       44   
151639  2022091200    3723  52435.0  Jordyn Brooks       45   
151640  2022091200    3723  52435.0  Jordyn Brooks       46   
151641  2022091200    3723  52435.0  Jordyn Brooks       47   
151642  2022091200    3723  52435.0  Jordyn Brooks       48   
151643  2022091200    3723  52435.0  Jordyn Brooks       49   
151644  2022091200    3723  52435.0  Jordyn Brooks       50   
151645  2022091200    3723  52435.0  Jordyn Brooks       51   
151646  2022091200    3723  52435.0  Jordyn Brooks       52   
151647  2022091200    3723  52435.0  Jordyn Brooks       53   
151648  2022091200    3723  52435.0  Jordyn Brooks       54   
151649  2022091200    3723  52435.0  Jordyn Brooks       55   
151650  2022091200    3723  52435.0  Jordyn Brooks       56   
151651  2022091200    3723  52435.0  Jordyn Brooks       57   
151652  2022091200    3723  52435.0  Jordyn Brooks       58   
151653  2022091200    3723  52435.0  Jordyn Brooks       59   
151654  2022091200    3723  52435.0  Jordyn Brooks       60   

                              time  jerseyNumber club playDirection      x  \
151595  2022-09-12 23:02:26.200000          56.0  SEA          left  65.56   
151596  2022

---

### **2.7: Generating Cosine and Alignment Features**

In [698]:
def compute_positional_features(df1, df2):
    """
    Function to compute averages based on certain conditions and add them as new columns to df1.
    Different conditions are applied based on the value of df1['event_type'].

    Args:
    df1 (pd.DataFrame): Dataframe to iterate through.
    df2 (pd.DataFrame): Dataframe to find the index and calculate averages.

    Returns:
    pd.DataFrame: Updated df1 with new columns.
    """
    # Initialize the new columns in df1
    df1['cos_avg_05'] = None
    df1['cos_avg_1'] = None
    df1['do_avg_05'] = None
    df1['do_avg_1'] = None
    df1['bc_do_avg_05'] = None
    df1['bc_do_avg_1'] = None

    # Iterate through each row in df1
    for index, row in df1.iterrows():
        # Print the index if it is a multiple of 1000
        if index % 1000 == 0:
            print(f"Processing index: {index}")

        # Determine the condition based on df1['event_type']
        if row['event_type'] == 1:
            condition = (df2['event'] == 'tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 2:
            condition = (df2['new_event'] == 'missed tackle') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 3:
            condition = (df2['event'] == 'fumble') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        elif row['event_type'] == 4:
            condition = (df2['event'] == 'first_contact') & \
                        (df2['game_play_Id'] == row['game_play_Id']) & \
                        (df2['nflId'] == row['nflId'])
        else:
            continue  # Skip the row if the event_type is neither 1,2, nor 3

        matching_indexes = df2.index[condition]

        # Checking if there are no matching indexes
        if len(matching_indexes) == 0:
            print(f"Index {index} has no matching index")
            continue
        # Checking if there is one matching index (What we want)
        elif len(matching_indexes) == 1:
            i = matching_indexes[0]
        # Checking to make sure there is only one matching index
        elif len(matching_indexes) > 1:
            print(f"Index {index} has more than one matching index")

        # Calculate averages and assign to df1
        df1.at[index, 'cos_avg_05'] = df2.loc[i-5:i-1, 'cosine'].mean()
        df1.at[index, 'cos_avg_1'] = df2.loc[i-10:i-6, 'cosine'].mean()
        df1.at[index, 'do_avg_05'] = df2.loc[i-5:i-1, 'do_align'].mean()
        df1.at[index, 'do_avg_1'] = df2.loc[i-10:i-6, 'do_align'].mean()
        df1.at[index, 'bc_do_avg_05'] = df2.loc[i-5:i-1, 'bc_do_align'].mean()
        df1.at[index, 'bc_do_avg_1'] = df2.loc[i-10:i-6, 'bc_do_align'].mean()

    return df1

In [572]:
tackles_1v1_1_all_features = compute_positional_features(tackles_1v1_1_newest, tracking_clean_1)

Processing index: 0
Processing index: 1000
Processing index: 2000
Processing index: 3000
Processing index: 4000
Processing index: 5000
Processing index: 6000
Processing index: 7000
Processing index: 8000
Processing index: 9000


In [573]:
tackles_1v1_1_all_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9725 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9725 non-null   int64  
 1   playId            9725 non-null   int64  
 2   nflId             9725 non-null   int64  
 3   tackle            9725 non-null   int64  
 4   assist            9725 non-null   int64  
 5   forcedFumble      9725 non-null   int64  
 6   pff_missedTackle  9725 non-null   int64  
 7   game_play_Id      9725 non-null   object 
 8   event_type        9725 non-null   float64
 9   s_avg_05          9725 non-null   float64
 10  s_avg_1           9725 non-null   float64
 11  bc_s_avg_05       9725 non-null   float64
 12  bc_s_avg_1        9725 non-null   float64
 13  cos_avg_05        9717 non-null   object 
 14  cos_avg_1         9721 non-null   object 
 15  do_avg_05         9725 non-null   object 
 16  do_avg_1          9725 non-null   object 


In [576]:
tackles_1v1_1_all_features.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tackles_1v1_1_all_features_rough.csv', index=False)

---

**Editing observations where player has missed tackle and tackle on same play**

In [652]:
# Get the unique 'game_play_Id' and 'nflId' values from double_tackles_original
game_play_ids = double_tackles_original['game_play_Id'].unique()
nfl_ids = double_tackles_original['nflId'].unique()

# Find the rows in tackles_1v1_1_all_features where 'event_type' is 2 and 'game_play_Id' and 'nflId' are in the lists
filtered_rows = tackles_1v1_1_all_features[(tackles_1v1_1_all_features['event_type'] == 2) & 
                                           (tackles_1v1_1_all_features['game_play_Id'].isin(game_play_ids)) & 
                                           (tackles_1v1_1_all_features['nflId'].isin(nfl_ids))]

In [653]:
# Change the 'event_type' values of the rows in filtered_rows to 4.0
filtered_rows['event_type'] = 4.0

# Reflect this change in the tackles_1v1_1_all_features DataFrame
tackles_1v1_1_all_features.loc[filtered_rows.index, 'event_type'] = 4.0

/var/folders/38/1m7d78r13mngspmlwjmj74480000gn/T/ipykernel_39743/281464958.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_rows['event_type'] = 4.0


In [680]:
tackles_1v1_1_all_features.event_type.value_counts()

event_type
1.0    7775
2.0    1859
3.0      59
4.0      32
Name: count, dtype: int64

In [679]:
tackles_1v1_1_af_drop5.event_type.value_counts()

event_type
1.0    7775
2.0    1859
3.0      59
4.0      27
Name: count, dtype: int64

In [678]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9712 non-null   object 
 14  cos_avg_1         9716 non-null   object 
 15  do_avg_05         9720 non-null   object 
 16  do_avg_1          9720 non-null   object 
 17  

---

**Looking into observations in which cosine features were not developed**

In [688]:
tackles_1v1_1_af_drop5[tackles_1v1_1_af_drop5['cos_avg_05'].isnull()]


gameId  playId  nflId  tackle  assist  forcedFumble  \
360   2022091102    1588  52563       1       0             0   
2978  2022100902    3966  44813       1       0             0   
3049  2022100202    1345  43780       1       0             0   
3927  2022101602    3745  47795       1       0             0   
4456  2022101300    3894  46077       1       0             0   
5374  2022102307    1266  46141       1       0             0   
6390  2022103012     525  43338       1       0             0   
7765  2022101611    3490  53504       1       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
360                  0  2022091102_1588         1.0     0.246    0.624   
2978                 0  2022100902_3966         1.0     0.000    0.008   
3049                 0  2022100202_1345         1.0     0.520    1.052   
3927                 0  2022101602_3745         1.0     0.294    0.184   
4456                 0  2022101300_3894         1.0     0.312    0.390   
5374                 0  2022102307_1266         1.0     0.238    0.548   
6390                 0   2022103012_525         1.0     0.194    0.594   
7765                 0  2022101611_3490         1.0     0.000    0.008   

      bc_s_avg_05  bc_s_avg_1 cos_avg_05 cos_avg_1 do_avg_05  do_avg_1  \
360         0.000       0.004        NaN -0.583413  0.428622  0.372556   
2978        0.646       0.398        NaN -0.672744 -0.225956 -0.054556   
3049        0.000       0.000        NaN       NaN  0.812267    0.9498   
3927        0.000       0.000        NaN       NaN -0.244133  0.363511   
4456        0.000       0.000        NaN       NaN  0.110111  0.075333   
5374        0.000       0.018        NaN  0.799925 -0.377244  0.056178   
6390        0.000       0.000        NaN       NaN  0.302444  0.441378   
7765        0.382       1.156        NaN  0.975531 -0.752067 -0.510711   

     bc_do_avg_05 bc_do_avg_1  
360      0.267333    0.295644  
2978     0.270889    0.192356  
3049    -0.634222   -0.592578  
3927    -0.268511   -0.015578  
4456    -0.284733   -0.242511  
5374    -0.059756    0.201178  
6390    -0.187622   -0.189867  
7765        0.387    0.729422

In [689]:
tackles_1v1_1_af_drop5['cos_05_null'] = 0
tackles_1v1_1_af_drop5.loc[tackles_1v1_1_af_drop5['cos_avg_05'].isnull(), 'cos_05_null'] = 1
tackles_1v1_1_af_drop5['cos_avg_05'].fillna(1, inplace=True)

In [690]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9716 non-null   object 
 15  do_avg_05         9720 non-null   object 
 16  do_avg_1          9720 non-null   object 
 17  

In [691]:
tackles_1v1_1_af_drop5[tackles_1v1_1_af_drop5['cos_avg_1'].isnull()]

gameId  playId  nflId  tackle  assist  forcedFumble  \
3049  2022100202    1345  43780       1       0             0   
3927  2022101602    3745  47795       1       0             0   
4456  2022101300    3894  46077       1       0             0   
6390  2022103012     525  43338       1       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
3049                 0  2022100202_1345         1.0     0.520    1.052   
3927                 0  2022101602_3745         1.0     0.294    0.184   
4456                 0  2022101300_3894         1.0     0.312    0.390   
6390                 0   2022103012_525         1.0     0.194    0.594   

      bc_s_avg_05  bc_s_avg_1  cos_avg_05 cos_avg_1 do_avg_05  do_avg_1  \
3049          0.0         0.0         1.0       NaN  0.812267    0.9498   
3927          0.0         0.0         1.0       NaN -0.244133  0.363511   
4456          0.0         0.0         1.0       NaN  0.110111  0.075333   
6390          0.0         0.0         1.0       NaN  0.302444  0.441378   

     bc_do_avg_05 bc_do_avg_1  cos_05_null  
3049    -0.634222   -0.592578            1  
3927    -0.268511   -0.015578            1  
4456    -0.284733   -0.242511            1  
6390    -0.187622   -0.189867            1

In [692]:
tackles_1v1_1_af_drop5['cos_1_null'] = 0
tackles_1v1_1_af_drop5.loc[tackles_1v1_1_af_drop5['cos_avg_1'].isnull(), 'cos_1_null'] = 1
tackles_1v1_1_af_drop5['cos_avg_1'].fillna(1, inplace=True)

In [693]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   object 
 16  do_avg_1          9720 non-null   object 
 17  

In [694]:
tackles_1v1_1_af_drop5.head(50)

gameId  playId  nflId  tackle  assist  forcedFumble  pff_missedTackle  \
0   2022090800     101  42816       1       0             0                 0   
1   2022090800     393  46232       1       0             0                 0   
2   2022090800     486  40166       1       0             0                 0   
3   2022090800     646  47939       1       0             0                 0   
4   2022090800     818  40107       1       0             0                 0   
5   2022090800    1736  44976       1       0             0                 0   
6   2022090800    2860  46085       1       0             0                 0   
7   2022090800    3145  52647       1       0             0                 0   
8   2022090800    3362  46190       1       0             0                 0   
9   2022090800    3383  54488       1       0             0                 0   
10  2022091100    1260  44851       1       0             0                 0   
11  2022091100    1672  40017       1       0             0                 0   
12  2022091100    2114  53469       1       0             0                 0   
13  2022091100    2353  38607       1       0             0                 0   
14  2022091100    2512  53611       1       0             0                 0   
15  2022091100    2640  44862       1       0             0                 0   
16  2022091100    2878  53489       1       0             0                 0   
17  2022091100    2899  37097       1       0             0                 0   
18  2022091100    3578  52542       1       0             0                 0   
19  2022091100    3647  53469       1       0             0                 0   
20  2022091100    3778  53489       1       0             0                 0   
21  2022091101    1744  44903       1       0             0                 0   
22  2022091101    1785  52452       1       0             0                 0   
23  2022091101    2051  46527       1       0             0                 0   
24  2022091101    3221  47799       1       0             0                 0   
25  2022091102      86  44938       1       0             0                 0   
26  2022091102     531  52571       1       0             0                 0   
27  2022091102     756  53609       1       0             0                 0   
28  2022091102    1493  54504       1       0             0                 0   
29  2022091102    2065  54504       1       0             0                 0   
30  2022091102    2352  46290       1       0             0                 0   
31  2022091102    2759  54504       1       0             0                 0   
32  2022091102    3783  52571       1       0             0                 0   
33  2022091103     520  46146       1       0             0                 0   
34  2022091103    1037  44842       1       0             0                 0   
35  2022091103    1315  46080       1       0             0                 0   
36  2022091103    2058  43641       1       0             0                 0   
37  2022091103    2222  44842       1       0             0                 0   
38  2022091103    2291  46698       1       0             0                 0   
39  2022091103    3147  44872       1       0             0                 0   
40  2022091103    3251  43325       1       0             0                 0   
41  2022091103    4175  43641       1       0             0                 0   
42  2022091103    4686  43641       1       0             0                 0   
43  2022091103    5096  43350       1       0             0                 0   
44  2022091104     803  52411       1       0             0                 0   
45  2022091104     910  54653       1       0             0                 0   
46  2022091104     999  47900       1       0             0                 0   
47  2022091104    2269  44888       1       0             0                 0   
48  2022091104    2974  47888       1  

---

### **2.8: Running Feature Generation for Final Time**

**Dropping old generated features**

In [695]:
tackles_1v1_1_af_drop5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   object 
 16  do_avg_1          9720 non-null   object 
 17  

In [696]:
tackles_1v1_1_ffg = tackles_1v1_1_af_drop5.drop(columns=['s_avg_05', 's_avg_1', 'bc_s_avg_05', 'bc_s_avg_1', 'cos_avg_05', 'cos_avg_1', 'do_avg_05', 'do_avg_1', 'bc_do_avg_05', 'bc_do_avg_1', 'cos_05_null', 'cos_1_null'])

In [697]:
tackles_1v1_1_ffg.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
dtypes: float64(1), int64(7), object(1)
memory usage: 759.4+ KB


**Computing Speed Features**

In [700]:
tackles_1v1_1_speed = compute_speed_features(tackles_1v1_1_ffg, tracking_clean_1)

Processing index: 0
Processing index: 1000
Processing index: 2000
Processing index: 3000
Processing index: 4000
Processing index: 5000
Processing index: 6000
Processing index: 7000
Processing index: 8000
Processing index: 9000


In [701]:
tackles_1v1_1_speed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   object 
 10  s_avg_1           9720 non-null   object 
 11  bc_s_avg_05       9720 non-null   object 
 12  bc_s_avg_1        9720 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 1.3+ MB


In [702]:
tackles_1v1_1_speed['s_avg_05'] = tackles_1v1_1_speed['s_avg_05'].astype(float)
tackles_1v1_1_speed['s_avg_1'] = tackles_1v1_1_speed['s_avg_1'].astype(float)
tackles_1v1_1_speed['bc_s_avg_05'] = tackles_1v1_1_speed['bc_s_avg_05'].astype(float)
tackles_1v1_1_speed['bc_s_avg_1'] = tackles_1v1_1_speed['bc_s_avg_1'].astype(float)


In [703]:
tackles_1v1_1_speed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
dtypes: float64(5), int64(7), object(1)
memory usage: 1.3+ MB


**Computing Positional Features**

In [704]:
tackles_1v1_1_af = compute_positional_features(tackles_1v1_1_speed, tracking_clean_1)

Processing index: 0
Processing index: 1000
Processing index: 2000
Processing index: 3000
Processing index: 4000
Processing index: 5000
Processing index: 6000
Processing index: 7000
Processing index: 8000
Processing index: 9000


In [705]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9712 non-null   object 
 14  cos_avg_1         9716 non-null   object 
 15  do_avg_05         9720 non-null   object 
 16  do_avg_1          9720 non-null   object 
 17  

In [706]:
tackles_1v1_1_af[tackles_1v1_1_af['cos_avg_05'].isnull()]

gameId  playId  nflId  tackle  assist  forcedFumble  \
360   2022091102    1588  52563       1       0             0   
2978  2022100902    3966  44813       1       0             0   
3049  2022100202    1345  43780       1       0             0   
3927  2022101602    3745  47795       1       0             0   
4456  2022101300    3894  46077       1       0             0   
5374  2022102307    1266  46141       1       0             0   
6390  2022103012     525  43338       1       0             0   
7765  2022101611    3490  53504       1       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
360                  0  2022091102_1588         1.0     0.246    0.624   
2978                 0  2022100902_3966         1.0     0.000    0.008   
3049                 0  2022100202_1345         1.0     0.520    1.052   
3927                 0  2022101602_3745         1.0     0.294    0.184   
4456                 0  2022101300_3894         1.0     0.312    0.390   
5374                 0  2022102307_1266         1.0     0.238    0.548   
6390                 0   2022103012_525         1.0     0.194    0.594   
7765                 0  2022101611_3490         1.0     0.000    0.008   

      bc_s_avg_05  bc_s_avg_1 cos_avg_05 cos_avg_1 do_avg_05  do_avg_1  \
360         0.000       0.004        NaN -0.583413  0.428622  0.372556   
2978        0.646       0.398        NaN -0.672744 -0.225956 -0.054556   
3049        0.000       0.000        NaN       NaN  0.812267    0.9498   
3927        0.000       0.000        NaN       NaN -0.244133  0.363511   
4456        0.000       0.000        NaN       NaN  0.110111  0.075333   
5374        0.000       0.018        NaN  0.799925 -0.377244  0.056178   
6390        0.000       0.000        NaN       NaN  0.302444  0.441378   
7765        0.382       1.156        NaN  0.975531 -0.752067 -0.510711   

     bc_do_avg_05 bc_do_avg_1  
360      0.267333    0.295644  
2978     0.270889    0.192356  
3049    -0.634222   -0.592578  
3927    -0.268511   -0.015578  
4456    -0.284733   -0.242511  
5374    -0.059756    0.201178  
6390    -0.187622   -0.189867  
7765        0.387    0.729422

In [707]:
tackles_1v1_1_af['cos_05_null'] = 0
tackles_1v1_1_af.loc[tackles_1v1_1_af['cos_avg_05'].isnull(), 'cos_05_null'] = 1
tackles_1v1_1_af['cos_avg_05'].fillna(0, inplace=True)

In [708]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9716 non-null   object 
 15  do_avg_05         9720 non-null   object 
 16  do_avg_1          9720 non-null   object 
 17  

In [709]:
tackles_1v1_1_af[tackles_1v1_1_af['cos_avg_1'].isnull()]

gameId  playId  nflId  tackle  assist  forcedFumble  \
3049  2022100202    1345  43780       1       0             0   
3927  2022101602    3745  47795       1       0             0   
4456  2022101300    3894  46077       1       0             0   
6390  2022103012     525  43338       1       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
3049                 0  2022100202_1345         1.0     0.520    1.052   
3927                 0  2022101602_3745         1.0     0.294    0.184   
4456                 0  2022101300_3894         1.0     0.312    0.390   
6390                 0   2022103012_525         1.0     0.194    0.594   

      bc_s_avg_05  bc_s_avg_1  cos_avg_05 cos_avg_1 do_avg_05  do_avg_1  \
3049          0.0         0.0         0.0       NaN  0.812267    0.9498   
3927          0.0         0.0         0.0       NaN -0.244133  0.363511   
4456          0.0         0.0         0.0       NaN  0.110111  0.075333   
6390          0.0         0.0         0.0       NaN  0.302444  0.441378   

     bc_do_avg_05 bc_do_avg_1  cos_05_null  
3049    -0.634222   -0.592578            1  
3927    -0.268511   -0.015578            1  
4456    -0.284733   -0.242511            1  
6390    -0.187622   -0.189867            1

In [710]:
tackles_1v1_1_af['cos_1_null'] = 0
tackles_1v1_1_af.loc[tackles_1v1_1_af['cos_avg_1'].isnull(), 'cos_1_null'] = 1
tackles_1v1_1_af['cos_avg_1'].fillna(0, inplace=True)

In [711]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   object 
 16  do_avg_1          9720 non-null   object 
 17  

In [712]:
tackles_1v1_1_af['do_avg_05'] = tackles_1v1_1_af['do_avg_05'].astype(float)
tackles_1v1_1_af['do_avg_1'] = tackles_1v1_1_af['do_avg_1'].astype(float)
tackles_1v1_1_af['bc_do_avg_05'] = tackles_1v1_1_af['bc_do_avg_05'].astype(float)
tackles_1v1_1_af['bc_do_avg_1'] = tackles_1v1_1_af['bc_do_avg_1'].astype(float)

In [713]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   float64
 16  do_avg_1          9720 non-null   float64
 17  

---
**Finding what plays had tackle and assist**

In [714]:
tackles_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17426 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   gameId            17426 non-null  int64 
 1   playId            17426 non-null  int64 
 2   nflId             17426 non-null  int64 
 3   tackle            17426 non-null  int64 
 4   assist            17426 non-null  int64 
 5   forcedFumble      17426 non-null  int64 
 6   pff_missedTackle  17426 non-null  int64 
 7   game_play_Id      17426 non-null  object
dtypes: int64(7), object(1)
memory usage: 1.1+ MB


In [675]:
###Adding 'game_play_Id' column to tackles_original
tackles_original = game_play_Id(tackles_original)

In [676]:
tackles_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17426 entries, 0 to 17425
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   gameId            17426 non-null  int64 
 1   playId            17426 non-null  int64 
 2   nflId             17426 non-null  int64 
 3   tackle            17426 non-null  int64 
 4   assist            17426 non-null  int64 
 5   forcedFumble      17426 non-null  int64 
 6   pff_missedTackle  17426 non-null  int64 
 7   game_play_Id      17426 non-null  object
dtypes: int64(7), object(1)
memory usage: 1.1+ MB


In [716]:
tackles_1v1_1_af.event_type.value_counts()

event_type
1.0    7775
2.0    1859
3.0      59
4.0      27
Name: count, dtype: int64

In [715]:
tackles_1v1_1_af.tackle.value_counts()

tackle
1    7834
0    1886
Name: count, dtype: int64

In [717]:
# Create an empty list to store the indices
assist_indices = []

# Iterate over the rows in tackles_1v1_1_af_drop5 where 'tackle' is 1
for index, row in tackles_1v1_1_af[tackles_1v1_1_af['tackle'] == 1].iterrows():
    # Find the rows in tackles_original where 'assist' is 1 and 'game_play_Id' is equal to the current row's value
    matching_rows = tackles_original[(tackles_original['assist'] == 1) & 
                                     (tackles_original['game_play_Id'] == row['game_play_Id'])]
    
    if len(matching_rows) > 1:
        print(f"Index {index} has more than one matching index")
    # If there are any matching rows, add the index to the list
    if not matching_rows.empty:
        assist_indices.append(index)

# Print the indices and the count
print(assist_indices)
print(len(assist_indices))

[4, 10, 17, 45, 47, 56, 61, 70, 71, 80, 88, 89, 91, 92, 96, 97, 104, 116, 119, 131, 140, 141, 156, 162, 170, 173, 174, 179, 180, 181, 183, 189, 202, 206, 212, 213, 220, 230, 234, 236, 247, 248, 265, 268, 269, 273, 276, 278, 289, 294, 301, 314, 317, 332, 342, 346, 359, 360, 363, 370, 374, 380, 390, 399, 402, 403, 409, 411, 428, 429, 431, 434, 438, 443, 460, 462, 476, 483, 488, 490, 492, 498, 511, 527, 533, 541, 548, 551, 554, 580, 581, 582, 584, 585, 586, 589, 592, 593, 596, 597, 607, 609, 610, 633, 636, 637, 639, 651, 655, 658, 659, 660, 665, 673, 680, 686, 688, 690, 691, 698, 703, 705, 707, 710, 721, 742, 747, 757, 761, 764, 772, 773, 782, 801, 808, 811, 817, 829, 830, 832, 833, 847, 876, 877, 880, 886, 889, 890, 892, 895, 898, 903, 923, 925, 935, 956, 957, 961, 965, 970, 971, 975, 978, 985, 1006, 1013, 1015, 1017, 1020, 1024, 1034, 1046, 1048, 1050, 1056, 1064, 1067, 1076, 1078, 1084, 1086, 1089, 1090, 1097, 1098, 1104, 1111, 1116, 1118, 1128, 1130, 1136, 1161, 1170, 1178, 1188, 1192

In [718]:
import pickle

# Specify the file path to save the .pkl file
file_path = 'assist_indices.pkl'

# Save assist_indices as a .pkl file
with open(folder_path + file_path, 'wb') as f:
    pickle.dump(assist_indices, f)


---

### **2.9: Confirming Event Type 4 Worked Correctly**

In [719]:
tackles_1v1_1_af[tackles_1v1_1_af['event_type'] == 4]

gameId  playId  nflId  tackle  assist  forcedFumble  \
357   2022091102     189  52571       0       0             0   
542   2022091105    2742  53450       0       0             0   
734   2022091110     750  52546       0       0             0   
958   2022091200    3723  52435       0       0             0   
981   2022091801    3061  41270       0       0             0   
1129  2022091801    2090  41270       0       0             0   
1937  2022092507    3091  47899       0       0             0   
2232  2022091812    2620  47804       0       0             0   
2294  2022092503    4086  38548       0       0             0   
2422  2022100206    2702  47913       0       0             0   
3068  2022100205    3163  47871       0       0             0   
3145  2022100902    1025  54543       0       0             0   
3413  2022100204     426  53592       0       0             0   
3701  2022100906    3322  54574       0       0             0   
3862  2022101700    2126  46264       0       0             0   
3879  2022100911    2608  39984       0       0             0   
4876  2022102300    2890  52627       0       0             0   
5078  2022102311    1564  38548       0       0             0   
5677  2022103009    2993  43358       0       0             0   
5749  2022110600    2782  52594       0       0             0   
6518  2022110601    3266  43503       0       0             0   
6527  2022110603     441  54653       0       0             0   
6783  2022102308     881  53509       0       0             0   
6882  2022103004     726  46669       0       0             0   
7168  2022100906    2763  52435       0       0             0   
7584  2022110605    1030  53450       0       0             0   
7623  2022110610    2875  47971       0       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
357                  1   2022091102_189         4.0     6.090    6.072   
542                  1  2022091105_2742         4.0     8.740    7.632   
734                  1   2022091110_750         4.0     6.672    6.850   
958                  1  2022091200_3723         4.0     8.172    8.002   
981                  1  2022091801_3061         4.0     2.622    2.930   
1129                 1  2022091801_2090         4.0     1.770    2.240   
1937                 1  2022092507_3091         4.0     4.826    6.444   
2232                 1  2022091812_2620         4.0     0.672    2.240   
2294                 1  2022092503_4086         4.0     6.756    5.780   
2422                 1  2022100206_2702         4.0     5.540    6.210   
3068                 1  2022100205_3163         4.0     5.062    5.662   
3145                 1  2022100902_1025         4.0     2.456    2.350   
3413                 1   2022100204_426         4.0     3.036    3.572   
3701                 1  2022100906_3322         4.0     9.552    9.756   
3862                 1  2022101700_2126         4.0     1.492    1.510   
3879                 1  2022100911_2608         4.0     4.876    4.506   
4876                 1  2022102300_2890         4.0     3.292    3.406   
5078                 1  2022102311_1564         4.0     5.922    5.208   
5677                 1  2022103009_2993         4.0     7.518    7.236   
5749                 1  2022110600_2782         4.0     7.694    6.336   
6518                 1  2022110601_3266         4.0     3.046    4.798   
6527                 1   2022110603_441         4.0     4.976    5.182   
6783                 1   2022102308_881         4.0     3.580    4.580   
6882                 1   2022103004_726         4.0     5.656    5.014   
7168                 1  2022100906_2763         4.0     6.980    6.498   
7584                 1  2022110605_1030         4.0     2.898    1.808   
7623                 1  2022110610_2875         4.0     4.908    5.890   

      bc_s_avg_05  bc_s_avg_1  cos_avg_05  cos_avg_1  do_avg_05  do_avg_1  \
357         8.956       8.974    0.9604

In [721]:
tracking_clean_1[(tracking_clean_1['game_play_Id'] == '2022091105_2742') & (tracking_clean_1['nflId'] == 53450)]

gameId  playId    nflId displayName  frameId  \
67806  2022091105    2742  53450.0  Kwity Paye        1   
67807  2022091105    2742  53450.0  Kwity Paye        2   
67808  2022091105    2742  53450.0  Kwity Paye        3   
67809  2022091105    2742  53450.0  Kwity Paye        4   
67810  2022091105    2742  53450.0  Kwity Paye        5   
67811  2022091105    2742  53450.0  Kwity Paye        6   
67812  2022091105    2742  53450.0  Kwity Paye        7   
67813  2022091105    2742  53450.0  Kwity Paye        8   
67814  2022091105    2742  53450.0  Kwity Paye        9   
67815  2022091105    2742  53450.0  Kwity Paye       10   
67816  2022091105    2742  53450.0  Kwity Paye       11   
67817  2022091105    2742  53450.0  Kwity Paye       12   
67818  2022091105    2742  53450.0  Kwity Paye       13   
67819  2022091105    2742  53450.0  Kwity Paye       14   
67820  2022091105    2742  53450.0  Kwity Paye       15   
67821  2022091105    2742  53450.0  Kwity Paye       16   
67822  2022091105    2742  53450.0  Kwity Paye       17   
67823  2022091105    2742  53450.0  Kwity Paye       18   
67824  2022091105    2742  53450.0  Kwity Paye       19   
67825  2022091105    2742  53450.0  Kwity Paye       20   
67826  2022091105    2742  53450.0  Kwity Paye       21   
67827  2022091105    2742  53450.0  Kwity Paye       22   
67828  2022091105    2742  53450.0  Kwity Paye       23   
67829  2022091105    2742  53450.0  Kwity Paye       24   
67830  2022091105    2742  53450.0  Kwity Paye       25   
67831  2022091105    2742  53450.0  Kwity Paye       26   
67832  2022091105    2742  53450.0  Kwity Paye       27   
67833  2022091105    2742  53450.0  Kwity Paye       28   
67834  2022091105    2742  53450.0  Kwity Paye       29   
67835  2022091105    2742  53450.0  Kwity Paye       30   
67836  2022091105    2742  53450.0  Kwity Paye       31   
67837  2022091105    2742  53450.0  Kwity Paye       32   
67838  2022091105    2742  53450.0  Kwity Paye       33   
67839  2022091105    2742  53450.0  Kwity Paye       34   
67840  2022091105    2742  53450.0  Kwity Paye       35   
67841  2022091105    2742  53450.0  Kwity Paye       36   
67842  2022091105    2742  53450.0  Kwity Paye       37   

                             time  jerseyNumber club playDirection      x  \
67806  2022-09-11 15:11:41.000000          51.0  IND         right  24.69   
67807  2022-09-11 15:11:41.099999          51.0  IND         right  24.49   
67808  2022-09-11 15:11:41.200000          51.0  IND         right  24.29   
67809  2022-09-11 15:11:41.299999          51.0  IND         right  24.09   
67810  2022-09-11 15:11:41.400000          51.0  IND         right  23.90   
67811  2022-09-11 15:11:41.500000          51.0  IND         right  23.73   
67812  2022-09-11 15:11:41.599999          51.0  IND         right  23.57   
67813  2022-09-11 15:11:41.700000          51.0  IND         right  23.43   
67814  2022-09-11 15:11:41.799999          51.0  IND         right  23.31   
67815  2022-09-11 15:11:41.900000          51.0  IND         right  23.20   
67816  2022-09-11 15:11:42.000000          51.0  IND         right  23.13   
67817  2022-09-11 15:11:42.099999          51.0  IND         right  23.07   
67818  2022-09-11 15:11:42.200000          51.0  IND         right  23.06   
67819  2022-09-11 15:11:42.299999          51.0  IND         right  23.10   
67820  2022-09-11 15:11:42.400000          51.0  IND         right  23.20   
67821  2022-09-11 15:11:42.500000          51.0  IND         right  23.34   
67822  2022-09-11 15:11:42.599999          51.0  IND         right  23.53   
67823  2022-09-11 15:11:42.700000          51.0  IND         right  23.74   
67824  2022-09-11 15:11:42.799999          51.0  IND         right  24.00   
67825  2022-09-11 15:11:42.900000          51.0  IND         right  24.29   
67826  2022-09-11 15:11:43.000000          51.0  IND         right  24.58   
67827  2022-09-11 15:11:43.099999          51.0  IND         right  24.88 

---

### **2.10: Adding `ballCarrierId` to feature_set df**

In [724]:
plays = pd.read_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/plays.csv')

In [725]:
plays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12486 entries, 0 to 12485
Data columns (total 35 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   gameId                            12486 non-null  int64  
 1   playId                            12486 non-null  int64  
 2   ballCarrierId                     12486 non-null  int64  
 3   ballCarrierDisplayName            12486 non-null  object 
 4   playDescription                   12486 non-null  object 
 5   quarter                           12486 non-null  int64  
 6   down                              12486 non-null  int64  
 7   yardsToGo                         12486 non-null  int64  
 8   possessionTeam                    12486 non-null  object 
 9   defensiveTeam                     12486 non-null  object 
 10  yardlineSide                      12319 non-null  object 
 11  yardlineNumber                    12486 non-null  int64  
 12  game

In [726]:
plays = game_play_Id(plays)

In [731]:
tackles_1v1_1_af.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9720 entries, 0 to 9724
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   float64
 16  do_avg_1          9720 non-null   float64
 17  

In [729]:
# Merge 'ballCarrierId' from plays to tackles_1v1_1_af based on 'game_play_Id'
tackles_1v1_1_af_wbc = tackles_1v1_1_af.merge(plays[['game_play_Id', 'ballCarrierId']], on='game_play_Id', how='left')

In [730]:
tackles_1v1_1_af_wbc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9720 entries, 0 to 9719
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gameId            9720 non-null   int64  
 1   playId            9720 non-null   int64  
 2   nflId             9720 non-null   int64  
 3   tackle            9720 non-null   int64  
 4   assist            9720 non-null   int64  
 5   forcedFumble      9720 non-null   int64  
 6   pff_missedTackle  9720 non-null   int64  
 7   game_play_Id      9720 non-null   object 
 8   event_type        9720 non-null   float64
 9   s_avg_05          9720 non-null   float64
 10  s_avg_1           9720 non-null   float64
 11  bc_s_avg_05       9720 non-null   float64
 12  bc_s_avg_1        9720 non-null   float64
 13  cos_avg_05        9720 non-null   float64
 14  cos_avg_1         9720 non-null   float64
 15  do_avg_05         9720 non-null   float64
 16  do_avg_1          9720 non-null   float64


In [735]:
tackles_1v1_1_af_wbc.tail()

gameId  playId  nflId  tackle  assist  forcedFumble  \
9715  2022103004     726  46669       1       0             0   
9716  2022100906    2763  52435       1       0             0   
9717  2022101604     699  38559       1       0             0   
9718  2022110605    1030  53450       1       0             0   
9719  2022110610    2875  47971       1       0             0   

      pff_missedTackle     game_play_Id  event_type  s_avg_05  s_avg_1  \
9715                 0   2022103004_726         1.0     3.294    7.262   
9716                 0  2022100906_2763         1.0     2.736    2.810   
9717                 0   2022101604_699         1.0     0.846    1.470   
9718                 0  2022110605_1030         1.0     0.640    0.266   
9719                 0  2022110610_2875         1.0     0.464    0.428   

      bc_s_avg_05  bc_s_avg_1  cos_avg_05  cos_avg_1  do_avg_05  do_avg_1  \
9715        4.748       6.432    0.838964   0.836698   0.263978  0.786644   
9716        2.584       1.656    0.917227   0.888187   0.970178  0.851956   
9717        4.854       3.626   -0.870827  -0.519733   0.156311  0.794000   
9718        0.490       0.828    0.280762  -0.134445   0.791756 -0.225911   
9719        3.584       2.914    0.847142  -0.278401   0.600622  0.568111   

      bc_do_avg_05  bc_do_avg_1  cos_05_null  cos_1_null  ballCarrierId  
9715     -0.281689     0.705556            0           0          43334  
9716      0.786600     0.801933            0           0          45244  
9717      0.567600     0.438711            0           0          53435  
9718     -0.390822    -0.175578            0           0          53549  
9719      0.612311     0.579533            0           0          40011

In [736]:
plays.loc[plays['game_play_Id'] == '2022110605_1030']

gameId  playId  ballCarrierId ballCarrierDisplayName  \
1412  2022110605    1030          53549    Rhamondre Stevenson   

                                        playDescription  quarter  down  \
1412  (10:54) R.Stevenson up the middle to IND 32 fo...        2     3   

      yardsToGo possessionTeam defensiveTeam yardlineSide  yardlineNumber  \
1412          1             NE           IND          IND              34   

     gameClock  preSnapHomeScore  preSnapVisitorScore passResult  passLength  \
1412     10:54                 3                    0        NaN         NaN   

      penaltyYards  prePenaltyPlayResult  playResult playNullifiedByPenalty  \
1412           NaN                     2           2                      N   

      absoluteYardlineNumber offenseFormation  defendersInTheBox  \
1412                      44            JUMBO                7.0   

      passProbability  preSnapHomeTeamWinProbability  \
1412         0.277017                        0.72826   

      preSnapVisitorTeamWinProbability  homeTeamWinProbabilityAdded  \
1412                           0.27174                     0.012378   

      visitorTeamWinProbilityAdded  expectedPoints  expectedPointsAdded  \
1412                     -0.012378        3.514937             0.400487   

     foulName1 foulName2  foulNFLId1  foulNFLId2     game_play_Id  
1412       NaN       NaN         NaN         NaN  2022110605_1030

### **2.10: Saving Finished Feature Set**

In [737]:
tackles_1v1_1_af_wbc.to_csv('/Users/alexiainman/Documents/Big Data Bowl/Data/Processed/tackles_feature_set_1.csv', index=False)